# Generated by Django 5.0.9 on 2026-05-08 20:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasources', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid_1c', models.UUIDField(blank=True, null=True)),
                ('article', models.CharField(max_length=100)),
                ('cross_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('oem_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('name', models.CharField(max_length=500)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('category_1c', models.CharField(blank=True, max_length=300)),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у')], default='new', max_length=10)),
                ('applicability', models.JSONField(default=list)),
                ('description_1c', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('warehouse', models.CharField(blank=True, max_length=200)),
                ('export_enabled', models.BooleanField(default=False)),
                ('sync_at', models.DateTimeField(blank=True, null=True)),
                ('hash_1c', models.CharField(blank=True, max_length=64)),
                ('datasource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='datasources.datasourceconnection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=500)),
                ('s3_key_thumb', models.CharField(blank=True, max_length=500)),
                ('url_source', models.URLField(blank=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'article'], name='products_pr_tenant__b874b6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'export_enabled', 'sync_at'], name='products_pr_tenant__778e5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('uuid_1c__isnull', False)), fields=('tenant', 'uuid_1c'), name='unique_tenant_uuid_1c'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'datasource', 'article'), name='unique_tenant_datasource_article'),
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'sha256')},
        ),
    ]
