# Generated by Django 5.0.9 on 2026-05-10 23:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_alter_datasourceconnection_options_and_more'),
        ('products', '0001_initial'),
        ('tenants', '0003_alter_apikey_created_at_alter_apikey_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AddField(
            model_name='product',
            name='image_status',
            field=models.CharField(blank=True, choices=[('', 'Не проверено'), ('has_images', 'Есть фото'), ('no_image', 'Нет фото'), ('searching', 'Идёт поиск')], default='', max_length=20, verbose_name='Статус изображений'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='file_size_kb',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла (KB)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='phash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Perceptual hash'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='quality_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Оценка качества (0–1)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='resolution_h',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота (px)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='resolution_w',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина (px)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_images', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='s3_key_preview',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ключ S3 (превью 600px)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='search_confidence',
            field=models.CharField(blank=True, choices=[('high', 'Высокая (по артикулу)'), ('medium', 'Средняя'), ('low', 'Низкая (по описанию)'), ('very_low', 'Очень низкая (нет артикула)')], max_length=10, verbose_name='Уверенность поиска'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='seo_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO-имя файла'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='source_id',
            field=models.CharField(blank=True, help_text='autodoc, exist, duckduckgo, 1c, csv, manual', max_length=50, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='status',
            field=models.CharField(choices=[('imported', 'Из источника'), ('auto_approved', 'Авто-одобрено'), ('needs_review', 'На проверке'), ('low_confidence', 'Низкая уверенность'), ('manually_set', 'Загружено вручную'), ('rejected', 'Отклонено')], default='imported', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='tier',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Приоритет источника'),
        ),
        migrations.AlterField(
            model_name='product',
            name='applicability',
            field=models.JSONField(default=list, verbose_name='Применимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=100, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=200, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_1c',
            field=models.CharField(blank=True, max_length=300, verbose_name='Категория из 1С'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у')], default='new', max_length=10, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cross_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Кросс-номера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='datasources.datasourceconnection', verbose_name='Источник данных'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_1c',
            field=models.TextField(blank=True, verbose_name='Описание из 1С'),
        ),
        migrations.AlterField(
            model_name='product',
            name='export_enabled',
            field=models.BooleanField(default=False, verbose_name='Экспорт на Avito'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hash_1c',
            field=models.CharField(blank=True, max_length=64, verbose_name='Хэш данных из 1С'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='oem_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='OEM-номера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена, ₽'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid_1c',
            field=models.UUIDField(blank=True, null=True, verbose_name='UUID из 1С'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.CharField(blank=True, max_length=200, verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='s3_key',
            field=models.CharField(max_length=500, verbose_name='Ключ S3'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='s3_key_thumb',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ключ S3 (миниатюра)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, verbose_name='SHA256'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружено'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url_source',
            field=models.URLField(blank=True, verbose_name='Исходный URL изображения'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['status', 'quality_score'], name='products_pr_status_fb2a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
    ]
