# Generated by Django 5.0.9 on 2026-05-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ai',
            field=models.TextField(blank=True, verbose_name='AI-описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ai',
            field=models.CharField(blank=True, max_length=300, verbose_name='AI-заголовок'),
        ),
    ]
