# Generated by Django 5.0.9 on 2026-05-27 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_enrichment_models'),
        ('tenants', '0003_alter_apikey_created_at_alter_apikey_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBulkActionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('action', models.CharField(choices=[('enrich_selected', 'Обогатить выбранные'), ('enrich_missing_data', 'Обогатить отсутствующие данные'), ('generate_descriptions', 'Сгенерировать описания'), ('enrich_then_generate_description', 'Обогатить и сгенерировать описания'), ('find_images', 'Найти изображения')], max_length=50, verbose_name='Действие')),
                ('source_id', models.CharField(default='tachka', max_length=50, verbose_name='Источник')),
                ('product_ids', models.JSONField(default=list, verbose_name='ID товаров')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Фильтры')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'В работе'), ('paused', 'На паузе'), ('cooling_down', 'Охлаждение'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=30, verbose_name='Статус')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='Всего')),
                ('queued_count', models.PositiveIntegerField(default=0, verbose_name='Поставлено в очередь')),
                ('processed_count', models.PositiveIntegerField(default=0, verbose_name='Обработано')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Успешно')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибки')),
                ('batch_size', models.PositiveIntegerField(default=20, verbose_name='Размер batch')),
                ('pause_seconds', models.PositiveIntegerField(default=60, verbose_name='Пауза между batch, сек')),
                ('next_batch_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующий batch')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bulk_action_jobs', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Массовое действие по товарам',
                'verbose_name_plural': 'Массовые действия по товарам',
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='products_pr_tenant__aba3cb_idx'), models.Index(fields=['status', '-created_at'], name='products_pr_status_b9de20_idx'), models.Index(fields=['tenant', 'status'], name='products_pr_tenant__87fc65_idx')],
            },
        ),
    ]
