# Generated by Django 5.0.9 on 2026-05-28 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productbulkactionjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPartRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('relation_type', models.CharField(choices=[('OEM', 'OEM'), ('Cross', 'Cross'), ('Analogue', 'Аналог'), ('Replacement', 'Замена'), ('Trade', 'Trade'), ('Unknown', 'Unknown')], default='Unknown', max_length=30, verbose_name='Тип связи')),
                ('source_id', models.CharField(blank=True, max_length=50, verbose_name='Источник')),
                ('source_url', models.URLField(blank=True, verbose_name='URL источника')),
                ('raw_text', models.TextField(blank=True, verbose_name='Исходный текст')),
                ('confidence', models.FloatField(default=1.0, verbose_name='Уверенность')),
                ('needs_review', models.BooleanField(default=False, verbose_name='Нужна проверка')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний раз найдено')),
            ],
            options={
                'verbose_name': 'Глобальная связь запчастей',
                'verbose_name_plural': 'Глобальные связи запчастей',
            },
        ),
        migrations.CreateModel(
            name='GlobalPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд/производитель')),
                ('normalized_brand', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Нормализованный бренд')),
                ('article', models.CharField(max_length=100, verbose_name='Артикул')),
                ('normalized_article', models.CharField(db_index=True, max_length=100, verbose_name='Нормализованный артикул')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Название из источника')),
                ('source_id', models.CharField(blank=True, max_length=50, verbose_name='Первичный источник')),
                ('source_url', models.URLField(blank=True, verbose_name='URL источника')),
                ('confidence', models.FloatField(default=1.0, verbose_name='Уверенность')),
                ('needs_review', models.BooleanField(default=False, verbose_name='Нужна проверка')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний раз найдено')),
            ],
            options={
                'verbose_name': 'Глобальная запчасть',
                'verbose_name_plural': 'Глобальные запчасти',
                'indexes': [models.Index(fields=['normalized_article'], name='products_gl_normali_ff05a1_idx'), models.Index(fields=['normalized_brand', 'normalized_article'], name='products_gl_normali_9e3b9e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='globalpart',
            constraint=models.UniqueConstraint(fields=('normalized_brand', 'normalized_article'), name='unique_global_part_identity'),
        ),
        migrations.AddField(
            model_name='globalpartrelation',
            name='source_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='products.globalpart', verbose_name='Исходная запчасть'),
        ),
        migrations.AddField(
            model_name='globalpartrelation',
            name='target_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='products.globalpart', verbose_name='Связанная запчасть'),
        ),
        migrations.AddIndex(
            model_name='globalpartrelation',
            index=models.Index(fields=['relation_type', 'source_id'], name='products_gl_relatio_af9c36_idx'),
        ),
        migrations.AddIndex(
            model_name='globalpartrelation',
            index=models.Index(fields=['source_part', 'relation_type'], name='products_gl_source__19ecd9_idx'),
        ),
        migrations.AddIndex(
            model_name='globalpartrelation',
            index=models.Index(fields=['target_part', 'relation_type'], name='products_gl_target__b1ddeb_idx'),
        ),
        migrations.AddConstraint(
            model_name='globalpartrelation',
            constraint=models.UniqueConstraint(fields=('source_part', 'target_part', 'relation_type', 'source_id'), name='unique_global_part_relation'),
        ),
    ]
