# Generated by Django 5.0.9 on 2026-05-28 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_global_part_knowledge_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPartFitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('make', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Марка')),
                ('model', models.CharField(db_index=True, max_length=150, verbose_name='Модель')),
                ('generation', models.CharField(blank=True, max_length=100, verbose_name='Поколение')),
                ('date_from', models.CharField(blank=True, max_length=20, verbose_name='Дата с')),
                ('date_to', models.CharField(blank=True, max_length=20, verbose_name='Дата по')),
                ('modification', models.CharField(blank=True, max_length=255, verbose_name='Модификация')),
                ('engine_code', models.CharField(blank=True, max_length=100, verbose_name='Код двигателя/кузова')),
                ('power_hp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность, л.с.')),
                ('source_id', models.CharField(blank=True, max_length=50, verbose_name='Источник')),
                ('source_url', models.URLField(blank=True, verbose_name='URL источника')),
                ('raw_text', models.TextField(blank=True, verbose_name='Исходная строка')),
                ('confidence', models.FloatField(default=1.0, verbose_name='Уверенность')),
                ('needs_review', models.BooleanField(default=False, verbose_name='Нужна проверка')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний раз найдено')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='products.globalpart', verbose_name='Глобальная запчасть')),
            ],
            options={
                'verbose_name': 'Глобальная применяемость',
                'verbose_name_plural': 'Глобальная применяемость',
                'indexes': [models.Index(fields=['make', 'model'], name='products_gl_make_2f79b3_idx'), models.Index(fields=['part', 'needs_review'], name='products_gl_part_id_9a9f1a_idx'), models.Index(fields=['source_id', 'needs_review'], name='products_gl_source__8cf9d2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='globalpartfitment',
            constraint=models.UniqueConstraint(fields=('part', 'source_id', 'make', 'model', 'generation', 'modification', 'engine_code', 'power_hp'), name='unique_global_part_fitment'),
        ),
    ]
