# Generated by Django 5.0.9 on 2026-05-28 20:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_global_part_fitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, verbose_name='Марка')),
                ('normalized_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Нормализованная марка')),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Алиасы')),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Марки авто',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='globalpartfitment',
            name='vehicle_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_fitments', to='products.vehiclemake', verbose_name='Нормализованная марка'),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=150, verbose_name='Модель')),
                ('normalized_name', models.CharField(db_index=True, max_length=150, verbose_name='Нормализованная модель')),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, size=None, verbose_name='Алиасы')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='products.vehiclemake', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
                'ordering': ['make__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='globalpartfitment',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_fitments', to='products.vehiclemodel', verbose_name='Нормализованная модель'),
        ),
        migrations.AddIndex(
            model_name='globalpartfitment',
            index=models.Index(fields=['vehicle_make', 'vehicle_model'], name='products_gl_vehicle_7d5f74_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('make', 'normalized_name'), name='unique_vehicle_model_per_make'),
        ),
    ]
