# Generated by Django 5.0.9 on 2026-05-28 21:55

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_vehicle_make_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('normalized_name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Нормализованная категория')),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, size=None, verbose_name='Алиасы')),
                ('fitment_required', models.BooleanField(default=True, verbose_name='Применяемость обязательна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.partcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория автозапчастей',
                'verbose_name_plural': 'Категории автозапчастей',
                'ordering': ['name'],
            },
        ),
    ]
