# Generated by Django 5.0.9 on 2026-05-28 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_catalog_domain_part_category'),
        ('tenants', '0005_add_mixed_catalog_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalogClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('domain', models.CharField(choices=[('auto_parts', 'Автозапчасть'), ('generic', 'Обычный товар'), ('jewellery', 'Украшение'), ('apparel', 'Одежда'), ('unknown', 'Не определено')], default='unknown', max_length=30, verbose_name='Домен товара')),
                ('confidence', models.FloatField(default=0, verbose_name='Уверенность')),
                ('source', models.CharField(choices=[('rules', 'Правила'), ('manual', 'Вручную'), ('ai', 'AI')], default='rules', max_length=30, verbose_name='Источник классификации')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('needs_review', models.BooleanField(default=False, verbose_name='Нужна проверка')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_classification', to='products.product', verbose_name='Товар')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_classifications', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Классификация товара',
                'verbose_name_plural': 'Классификации товаров',
                'indexes': [models.Index(fields=['tenant', 'domain'], name='products_pr_tenant__089a3b_idx'), models.Index(fields=['tenant', 'needs_review'], name='products_pr_tenant__1e71de_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productcatalogclassification',
            constraint=models.UniqueConstraint(fields=('tenant', 'product'), name='unique_product_catalog_classification'),
        ),
    ]
