# Generated by Django 5.0.9 on 2026-05-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_catalog_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbulkactionjob',
            name='action',
            field=models.CharField(choices=[('enrich_selected', 'Обогатить выбранные'), ('enrich_missing_data', 'Обогатить отсутствующие данные'), ('generate_descriptions', 'Сгенерировать описания'), ('enrich_then_generate_description', 'Обогатить и сгенерировать описания'), ('classify_catalog_domain', 'Определить домен товаров'), ('find_images', 'Найти изображения')], max_length=50, verbose_name='Действие'),
        ),
    ]
