# Generated by Django 5.0.9 on 2026-05-30 19:24

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_bulk_classification_action'),
        ('tenants', '0005_add_mixed_catalog_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('normalized_name', models.CharField(db_index=True, max_length=200, verbose_name='Нормализованное название')),
                ('domain', models.CharField(choices=[('auto_parts', 'Автозапчасти'), ('generic', 'Обычный товар'), ('jewellery', 'Украшения'), ('apparel', 'Одежда'), ('unknown', 'Не определено')], default='unknown', max_length=30, verbose_name='Домен')),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, size=None, verbose_name='Алиасы')),
                ('external_source', models.CharField(blank=True, max_length=50, verbose_name='Источник')),
                ('external_id', models.CharField(blank=True, max_length=150, verbose_name='Внешний ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.tenantcatalogcategory', verbose_name='Родительская категория')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_categories', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Категория каталога tenant-а',
                'verbose_name_plural': 'Категории каталога tenant-а',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='catalog_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.tenantcatalogcategory', verbose_name='Категория каталога'),
        ),
        migrations.CreateModel(
            name='TenantCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('source_category', models.CharField(max_length=300, verbose_name='Категория источника')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='products.tenantcatalogcategory', verbose_name='Категория tenant-а')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_category_mappings', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Маппинг категории каталога',
                'verbose_name_plural': 'Маппинги категорий каталога',
                'ordering': ['source_category'],
            },
        ),
        migrations.AddConstraint(
            model_name='tenantcatalogcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('tenant', 'normalized_name'), name='unique_root_tenant_catalog_category_name'),
        ),
        migrations.AddConstraint(
            model_name='tenantcatalogcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('tenant', 'parent', 'normalized_name'), name='unique_child_tenant_catalog_category_name'),
        ),
        migrations.AddConstraint(
            model_name='tenantcategorymapping',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_category'), name='unique_tenant_catalog_category_mapping'),
        ),
    ]
