# Generated by Django 5.0.9 on 2026-05-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_tenant_catalog_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcatalogcategory',
            name='default_image_s3_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='Картинка категории по умолчанию'),
        ),
        migrations.AddField(
            model_name='tenantcatalogcategory',
            name='default_image_source_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя файла картинки по умолчанию'),
        ),
        migrations.AlterField(
            model_name='productcatalogclassification',
            name='domain',
            field=models.CharField(default='unknown', max_length=50, verbose_name='Домен товара'),
        ),
        migrations.AlterField(
            model_name='tenantcatalogcategory',
            name='domain',
            field=models.CharField(default='unknown', max_length=50, verbose_name='Домен'),
        ),
    ]
