# Generated by Django 5.0.9 on 2026-05-31 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_operator_review_status'),
        ('tenants', '0007_tenantcatalogdomain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcatalogcategory',
            name='root_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_catalog_categories', to='tenants.catalogdomain', verbose_name='Корневая категория'),
        ),
        migrations.AddIndex(
            model_name='tenantcatalogcategory',
            index=models.Index(fields=['tenant', 'root_domain'], name='products_te_tenant__8c7364_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcatalogcategory',
            index=models.Index(fields=['tenant', 'root_domain', 'is_active'], name='products_te_tenant__5190d0_idx'),
        ),
    ]
