# Generated by Django 5.0.9 on 2026-05-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_seed_base_part_categories'),
        ('tenants', '0007_tenantcatalogdomain_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenantcatalogcategory',
            name='unique_root_tenant_catalog_category_name',
        ),
        migrations.AddConstraint(
            model_name='tenantcatalogcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('tenant', 'root_domain', 'normalized_name'), name='unique_root_tenant_catalog_category_name'),
        ),
    ]
