# Generated by Django 5.0.9 on 2026-05-31 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_alter_datasourceconnection_options_and_more'),
        ('products', '0019_seed_catalog_category_templates'),
        ('tenants', '0008_seed_base_catalog_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrandAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('alias', models.CharField(max_length=150, verbose_name='Алиас')),
                ('normalized_alias', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Нормализованный алиас')),
                ('source_id', models.CharField(blank=True, max_length=50, verbose_name='Источник')),
                ('confidence', models.FloatField(default=1.0, verbose_name='Уверенность')),
                ('needs_review', models.BooleanField(default=False, verbose_name='Нужна проверка')),
            ],
            options={
                'verbose_name': 'Алиас бренда',
                'verbose_name_plural': 'Алиасы брендов',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('normalized_name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Нормализованное название')),
                ('source_id', models.CharField(blank=True, max_length=50, verbose_name='Источник')),
                ('confidence', models.FloatField(default=1.0, verbose_name='Уверенность')),
                ('needs_review', models.BooleanField(default=False, verbose_name='Нужна проверка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('domains', models.ManyToManyField(blank=True, related_name='product_brands', to='tenants.catalogdomain', verbose_name='Корневые категории')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='globalpart',
            name='brand_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_parts', to='products.productbrand', verbose_name='Нормализованный бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productbrand', verbose_name='Нормализованный бренд'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'brand_ref'], name='products_pr_tenant__6135aa_idx'),
        ),
        migrations.AddField(
            model_name='productbrandalias',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_aliases', to='products.productbrand', verbose_name='Бренд'),
        ),
        migrations.AddIndex(
            model_name='productbrand',
            index=models.Index(fields=['normalized_name'], name='products_pr_normali_d9fd09_idx'),
        ),
        migrations.AddIndex(
            model_name='productbrand',
            index=models.Index(fields=['is_active', 'name'], name='products_pr_is_acti_1b90b9_idx'),
        ),
        migrations.AddIndex(
            model_name='productbrandalias',
            index=models.Index(fields=['normalized_alias'], name='products_pr_normali_84efa3_idx'),
        ),
        migrations.AddIndex(
            model_name='productbrandalias',
            index=models.Index(fields=['brand', 'needs_review'], name='products_pr_brand_i_d17875_idx'),
        ),
    ]
