# Generated by Django 5.0.9 on 2026-06-01 06:47

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_backfill_product_brand_refs'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, verbose_name='Поколение')),
                ('normalized_name', models.CharField(db_index=True, max_length=100, verbose_name='Нормализованное поколение')),
                ('body_code', models.CharField(blank=True, max_length=50, verbose_name='Код кузова')),
                ('date_from', models.CharField(blank=True, max_length=20, verbose_name='Дата с')),
                ('date_to', models.CharField(blank=True, max_length=20, verbose_name='Дата по')),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Алиасы')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='products.vehiclemodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Поколение авто',
                'verbose_name_plural': 'Поколения авто',
                'ordering': ['model__make__name', 'model__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='globalpartfitment',
            name='vehicle_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_fitments', to='products.vehiclegeneration', verbose_name='Нормализованное поколение'),
        ),
        migrations.AddIndex(
            model_name='globalpartfitment',
            index=models.Index(fields=['vehicle_model', 'vehicle_generation'], name='products_gl_vehicle_bfe166_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclegeneration',
            index=models.Index(fields=['model', 'normalized_name'], name='products_ve_model_i_d7c716_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclegeneration',
            index=models.Index(fields=['body_code'], name='products_ve_body_co_08a9bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiclegeneration',
            constraint=models.UniqueConstraint(fields=('model', 'normalized_name'), name='unique_vehicle_generation_per_model'),
        ),
    ]
