# Generated by Django 5.0.9 on 2026-08-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_brand_resolution_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenrichmentfact',
            name='fact_type',
            field=models.CharField(choices=[('brand', 'Предполагаемый бренд'), ('technical', 'Технический'), ('fitment', 'Применяемость'), ('oem', 'OEM/Cross'), ('description_hint', 'Подсказка для описания'), ('warning', 'Предупреждение')], max_length=30, verbose_name='Тип факта'),
        ),
    ]
