# Generated by Django 5.0.9 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_bulk_job_dispatch_recovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalogclassification',
            name='source',
            field=models.CharField(
                choices=[
                    ('rules', 'Правила'),
                    ('manual', 'Вручную'),
                    ('api_key', 'API Key'),
                    ('ai', 'AI'),
                ],
                default='rules',
                max_length=30,
                verbose_name='Источник классификации',
            ),
        ),
    ]
