# Generated by Django 5.2.17 on 2026-08-30 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_product_physical_profile'),
        ('tenants', '0016_webhook_delivery_claim_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productphysicalprofile',
            name='map_provenance',
            field=models.JSONField(blank=True, default=dict, verbose_name='Источники подтверждённых данных MAP'),
        ),
        migrations.CreateModel(
            name='ProductPhysicalSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('field', models.CharField(choices=[('barcode', 'Штрихкод'), ('length_mm', 'Длина, мм'), ('width_mm', 'Ширина, мм'), ('height_mm', 'Высота, мм'), ('weight_g', 'Вес, г')], max_length=20, verbose_name='Поле')),
                ('value', models.CharField(max_length=64, verbose_name='Значение в единицах MAP')),
                ('source_id', models.CharField(max_length=50, verbose_name='Источник')),
                ('source_url', models.URLField(blank=True, verbose_name='URL источника')),
                ('raw_name', models.CharField(blank=True, max_length=150, verbose_name='Исходное название')),
                ('raw_value', models.TextField(blank=True, verbose_name='Исходное значение')),
                ('confidence', models.FloatField(default=0.8, verbose_name='Уверенность')),
                ('is_current', models.BooleanField(default=True, verbose_name='Найдено в последнем запуске')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний раз найдено')),
                ('review_status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус проверки')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_suggestions', to='products.product', verbose_name='Товар')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_physical_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_physical_suggestions', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Предложение физических данных товара',
                'verbose_name_plural': 'Предложения физических данных товаров',
                'indexes': [models.Index(fields=['tenant', 'product', 'is_current'], name='prd_phys_sugg_current_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'product', 'source_id', 'field'), name='unique_product_physical_suggestion')],
            },
        ),
    ]
