# Generated by Django 5.0.9 on 2026-08-04 20:50

import apps.media_processing.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0028_nullable_inherited_category_margin'),
        ('tenants', '0011_tenant_ai_credit_limit_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaProviderPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider_id', models.SlugField(unique=True, verbose_name='Провайдер')),
                ('display_name', models.CharField(max_length=120, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('priority', models.PositiveSmallIntegerField(default=100, verbose_name='Приоритет')),
                ('capabilities', models.JSONField(default=list, verbose_name='Возможности')),
                ('allowed_plan_slugs', models.JSONField(blank=True, default=list, help_text='Пустой список — доступен всем тарифам.', verbose_name='Доступен тарифам')),
                ('operation_credit_costs', models.JSONField(blank=True, default=dict, verbose_name='Стоимость операций в AI-кредитах')),
                ('requests_per_minute', models.PositiveIntegerField(default=60, verbose_name='Лимит запросов в минуту')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Политика медиа-провайдера',
                'verbose_name_plural': 'Политики медиа-провайдеров',
                'ordering': ['priority', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='MediaProcessingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=80, verbose_name='Slug')),
                ('operations', models.JSONField(default=list, validators=[apps.media_processing.models._validate_operations], verbose_name='Операции')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('provider_preferences', models.JSONField(blank=True, default=list, verbose_name='Приоритет провайдеров')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_processing_presets', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Пресет обработки медиа',
                'verbose_name_plural': 'Пресеты обработки медиа',
                'ordering': ['tenant_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('operations', models.JSONField(default=list, validators=[apps.media_processing.models._validate_operations], verbose_name='Операции')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('provider_id', models.SlugField(blank=True, verbose_name='Провайдер')),
                ('provider_job_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID задачи провайдера')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('submitted', 'Передано провайдеру'), ('processing', 'Обрабатывается'), ('succeeded', 'Готово'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], db_index=True, default='queued', max_length=20, verbose_name='Статус')),
                ('idempotency_key', models.CharField(default=uuid.uuid4, editable=False, max_length=64, verbose_name='Ключ идемпотентности')),
                ('provider_metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные провайдера')),
                ('estimated_credits', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Оценка кредитов')),
                ('charged_credits', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Списано кредитов')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='Код ошибки')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='products.productimage', verbose_name='Исходное изображение')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_media_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Запустил')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_processing_jobs', to='tenants.tenant', verbose_name='Тенант')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='media_processing.mediaprocessingpreset', verbose_name='Пресет')),
            ],
            options={
                'verbose_name': 'Задача обработки медиа',
                'verbose_name_plural': 'Задачи обработки медиа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImageVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider_id', models.SlugField(blank=True, verbose_name='Провайдер')),
                ('operations', models.JSONField(blank=True, default=list, verbose_name='Операции')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('s3_key', models.CharField(max_length=500, verbose_name='Ключ S3')),
                ('content_type', models.CharField(default='image/jpeg', max_length=100, verbose_name='Content-Type')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота')),
                ('file_size_kb', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла (KB)')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA256')),
                ('is_active', models.BooleanField(default=False, verbose_name='Используется для публикации')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='media_processing.mediaprocessingjob', verbose_name='Задача')),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.productimage', verbose_name='Исходное изображение')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image_variants', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Вариант изображения товара',
                'verbose_name_plural': 'Варианты изображений товаров',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider_preferences', models.JSONField(blank=True, default=dict, help_text='Ключ — операция или *, значение — список provider_id.', verbose_name='Приоритеты провайдеров')),
                ('auto_process_manual_uploads', models.BooleanField(default=False, verbose_name='Автообработка ручных загрузок')),
                ('auto_process_approved_search', models.BooleanField(default=False, verbose_name='Автообработка одобренных результатов поиска')),
                ('allow_generative_operations', models.BooleanField(default=False, verbose_name='Разрешить генеративные операции')),
                ('default_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_tenants', to='media_processing.mediaprocessingpreset', verbose_name='Пресет по умолчанию')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_settings', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Настройки медиа тенанта',
                'verbose_name_plural': 'Настройки медиа тенантов',
            },
        ),
        migrations.CreateModel(
            name='ImageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('source_url', models.URLField(blank=True, max_length=2000, verbose_name='URL кандидата')),
                ('source_id', models.CharField(blank=True, max_length=50, verbose_name='Источник')),
                ('provider_id', models.SlugField(blank=True, verbose_name='Провайдер проверки')),
                ('model_id', models.CharField(blank=True, max_length=150, verbose_name='Модель/версия')),
                ('verdict', models.CharField(choices=[('accept', 'Подходит'), ('review', 'Нужна проверка'), ('reject', 'Не подходит'), ('error', 'Ошибка проверки')], db_index=True, default='review', max_length=20, verbose_name='Решение')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Оценка 0–1')),
                ('reason_codes', models.JSONField(blank=True, default=list, verbose_name='Причины')),
                ('checks', models.JSONField(blank=True, default=dict, verbose_name='Проверки')),
                ('expected_product', models.JSONField(blank=True, default=dict, verbose_name='Ожидаемые данные товара')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Ответ провайдера')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assessments', to='products.product', verbose_name='Товар')),
                ('product_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='products.productimage', verbose_name='Изображение товара')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assessments', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Проверка изображения',
                'verbose_name_plural': 'Проверки изображений',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'verdict', '-created_at'], name='media_proce_tenant__709101_idx'), models.Index(fields=['product', '-created_at'], name='media_proce_product_e92138_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mediaprocessingpreset',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'slug'), name='unique_tenant_media_preset_slug'),
        ),
        migrations.AddConstraint(
            model_name='mediaprocessingpreset',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('slug',), name='unique_platform_media_preset_slug'),
        ),
        migrations.AddConstraint(
            model_name='mediaprocessingpreset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('tenant__isnull', False)), fields=('tenant',), name='unique_default_tenant_media_preset'),
        ),
        migrations.AddConstraint(
            model_name='mediaprocessingpreset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('tenant__isnull', True)), fields=('is_default',), name='unique_default_platform_media_preset'),
        ),
        migrations.AddIndex(
            model_name='mediaprocessingjob',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='media_proce_tenant__6ef34c_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaprocessingjob',
            index=models.Index(fields=['product_image', '-created_at'], name='media_proce_product_2b4e68_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaprocessingjob',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='unique_tenant_media_job_idempotency'),
        ),
        migrations.AddIndex(
            model_name='productimagevariant',
            index=models.Index(fields=['tenant', '-created_at'], name='media_proce_tenant__9c4af4_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimagevariant',
            constraint=models.UniqueConstraint(fields=('product_image', 'sha256'), name='unique_product_image_variant_sha'),
        ),
        migrations.AddConstraint(
            model_name='productimagevariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product_image',), name='unique_active_product_image_variant'),
        ),
    ]
