# Generated by Django 5.0.9 on 2026-06-06 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0010_rename_generic_mixed_domain_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма, ₽'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_s3_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ключ PDF в S3'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID платежа ЮKassa'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limit_ai_credits',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит AI-кредитов'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limit_listings',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит листингов'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limit_sku',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит SKU'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в месяц'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_yearly',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в год'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Ежемесячно'), ('yearly', 'Ежегодно')], default='monthly', max_length=10, verbose_name='Период оплаты'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateField(verbose_name='Конец периода'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateField(verbose_name='Начало периода'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan', verbose_name='Тарифный план'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Пробный период'), ('active', 'Активна'), ('past_due', 'Просрочена'), ('cancelled', 'Отменена')], default='trial', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='yookassa_subscription_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID подписки ЮKassa'),
        ),
    ]
