# Generated by Django 5.0.9 on 2026-07-29 17:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_aiusagelog_created_at_and_more'),
        ('tenants', '0010_rename_generic_mixed_domain_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Пакет AI-кредитов',
                'verbose_name_plural': 'Пакеты AI-кредитов',
                'ordering': ['sort_order', 'credits'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_type',
            field=models.CharField(choices=[('subscription', 'Подписка'), ('ai_topup', 'Пополнение AI-баланса')], default='subscription', max_length=20, verbose_name='Тип покупки'),
        ),
        migrations.CreateModel(
            name='AIWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('included_balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('purchased_balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('reserved_balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('included_expires_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_wallet', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'AI-кошелёк',
                'verbose_name_plural': 'AI-кошельки',
            },
        ),
        migrations.CreateModel(
            name='AICreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('grant', 'Начисление по подписке'), ('topup', 'Покупка кредитов'), ('reserve', 'Резерв'), ('release', 'Возврат резерва'), ('charge', 'Списание'), ('expire', 'Сгорание'), ('adjustment', 'Корректировка')], max_length=20)),
                ('balance_type', models.CharField(choices=[('included', 'Включённый баланс'), ('purchased', 'Купленный баланс'), ('reserved', 'Резерв')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=160)),
                ('reference', models.CharField(blank=True, max_length=160)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_transactions', to='tenants.tenant')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.aiwallet')),
            ],
            options={
                'verbose_name': 'Проводка AI-кредитов',
                'verbose_name_plural': 'Проводки AI-кредитов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='billing_aic_tenant__fd19fa_idx'), models.Index(fields=['tenant', 'idempotency_key'], name='billing_aic_tenant__e45743_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='aicredittransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='unique_tenant_ai_credit_idempotency_key'),
        ),
    ]
