# Generated by Django 5.0.9 on 2026-07-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_set_full_yearly_plan_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ai_period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Конец периода AI-кредитов'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ai_period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало периода AI-кредитов'),
        ),
    ]
