# Generated by Django 5.0.9 on 2026-07-29 20:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_backfill_subscription_ai_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiwallet',
            name='included_limit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='aiwallet',
            name='notification_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
