# Generated by Django 5.0.9 on 2026-07-29 21:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_limit_enterprise_ai_credits'),
        ('tenants', '0011_tenant_ai_credit_limit_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='refund_review_required',
            field=models.BooleanField(default=False, verbose_name='Возврат требует ручной проверки'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Возвращено'),
        ),
        migrations.AlterField(
            model_name='aicredittransaction',
            name='kind',
            field=models.CharField(choices=[('grant', 'Начисление по подписке'), ('topup', 'Покупка кредитов'), ('reserve', 'Резерв'), ('release', 'Возврат резерва'), ('charge', 'Списание'), ('expire', 'Сгорание'), ('adjustment', 'Корректировка'), ('refund', 'Возврат платежа'), ('chargeback', 'Чарджбэк')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('partially_refunded', 'Частично возвращён'), ('refunded', 'Возвращён'), ('manual_review', 'Требует ручной проверки')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='PaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('refund', 'Возврат'), ('chargeback', 'Чарджбэк')], max_length=20)),
                ('provider_reference', models.CharField(max_length=200, unique=True)),
                ('payment_id', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('credits_requested', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('credits_reversed', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('credit_shortfall', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('status', models.CharField(choices=[('applied', 'Применён'), ('manual_review', 'Ручная проверка'), ('rejected', 'Отклонён')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Возврат/чарджбэк',
                'verbose_name_plural': 'Возвраты и чарджбэки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(default='yookassa', max_length=30)),
                ('event_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=200)),
                ('payment_id', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('decision', models.CharField(choices=[('received', 'Получен'), ('applied', 'Применён'), ('ignored', 'Игнорирован'), ('rejected', 'Отклонён'), ('manual_review', 'Ручная проверка'), ('error', 'Ошибка')], default='received', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('delivery_count', models.PositiveIntegerField(default=1)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='billing.invoice')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_webhook_events', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Webhook биллинга',
                'verbose_name_plural': 'Webhook биллинга',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'event_type', '-created_at'], name='billing_bil_provide_d461aa_idx'), models.Index(fields=['payment_id', '-created_at'], name='billing_bil_payment_492949_idx'), models.Index(fields=['decision', '-created_at'], name='billing_bil_decisio_44c63f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='billingwebhookevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('provider', 'idempotency_key'), name='unique_provider_billing_webhook_event'),
        ),
        migrations.AddIndex(
            model_name='paymentreversal',
            index=models.Index(fields=['invoice', '-created_at'], name='billing_pay_invoice_8c748b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreversal',
            index=models.Index(fields=['payment_id', '-created_at'], name='billing_pay_payment_db3b27_idx'),
        ),
    ]
