# Generated by Django 5.0.9 on 2026-05-08 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('1c_http', '1С HTTP'), ('1c_xml', '1С XML'), ('csv', 'CSV/Excel')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('credentials', models.BinaryField()),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(default='never', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasource_connections', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
