# Generated by Django 5.0.9 on 2026-05-10 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
        ('tenants', '0003_alter_apikey_created_at_alter_apikey_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasourceconnection',
            options={'ordering': ['name'], 'verbose_name': 'Источник данных', 'verbose_name_plural': 'Источники данных'},
        ),
        migrations.AlterField(
            model_name='datasourceconnection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='datasourceconnection',
            name='credentials',
            field=models.BinaryField(verbose_name='Учётные данные (зашифровано)'),
        ),
        migrations.AlterField(
            model_name='datasourceconnection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='datasourceconnection',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='Последняя ошибка'),
        ),
        migrations.AlterField(
            model_name='datasourceconnection',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация'),
        ),
        migrations.AlterField(
            model_name='datasourceconnection',
            name='last_sync_status',
            field=models.CharField(default='never', max_length=20, verbose_name='Статус последней синхронизации'),
        ),
        migrations.AlterField(
            model_name='datasourceconnection',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='datasourceconnection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasource_connections', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AlterField(
            model_name='datasourceconnection',
            name='type',
            field=models.CharField(choices=[('1c_http', '1С HTTP'), ('1c_xml', '1С XML'), ('csv', 'CSV/Excel')], max_length=20, verbose_name='Тип источника'),
        ),
        migrations.AlterField(
            model_name='datasourceconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
