# Generated by Django 5.0.9 on 2026-07-29 17:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0010_rename_generic_mixed_domain_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], max_length=20)),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('quality_tier', models.CharField(choices=[('standard', 'Стандарт'), ('advanced', 'Повышенное'), ('maximum', 'Максимальное')], default='standard', max_length=20)),
                ('speed_tier', models.CharField(choices=[('fast', 'Быстрая'), ('balanced', 'Средняя'), ('slow', 'Медленная')], default='balanced', max_length=20)),
                ('supported_tasks', models.JSONField(default=list)),
                ('input_credits_per_million', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('cached_input_credits_per_million', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('output_credits_per_million', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('minimum_credits', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12)),
                ('max_output_tokens', models.PositiveIntegerField(default=2048)),
                ('reasoning_effort', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_fallback', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'AI-модель',
                'verbose_name_plural': 'AI-модели',
                'ordering': ['sort_order', 'display_name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='ai_agent_ai_is_acti_3cd3ba_idx'), models.Index(fields=['provider', 'is_active'], name='ai_agent_ai_provide_f15897_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('use_task_overrides', models.BooleanField(default=False)),
                ('default_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_tenants', to='ai_agent.aimodel')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Настройки AI тенанта',
                'verbose_name_plural': 'Настройки AI тенантов',
            },
        ),
        migrations.CreateModel(
            name='TenantAITaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('task_type', models.CharField(choices=[('description_generation', 'Генерация описаний'), ('classification', 'Классификация товаров'), ('attribute_extraction', 'Извлечение характеристик'), ('fitment_resolution', 'Анализ совместимости')], max_length=40)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_overrides', to='ai_agent.aimodel')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_models', to='ai_agent.tenantaisettings')),
            ],
            options={
                'verbose_name': 'Модель AI-задачи',
                'verbose_name_plural': 'Модели AI-задач',
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('task_type', models.CharField(choices=[('description_generation', 'Генерация описаний'), ('classification', 'Классификация товаров'), ('attribute_extraction', 'Извлечение характеристик'), ('fitment_resolution', 'Анализ совместимости')], max_length=40)),
                ('provider', models.CharField(max_length=20)),
                ('model_id', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка провайдера'), ('rejected', 'Ответ отклонён валидатором')], max_length=20)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('cached_input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('charged_credits', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_request_logs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'AI-запрос',
                'verbose_name_plural': 'AI-запросы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='ai_agent_ai_tenant__1e8697_idx'), models.Index(fields=['tenant', 'task_type', '-created_at'], name='ai_agent_ai_tenant__9fa514_idx'), models.Index(fields=['provider', 'model_id', '-created_at'], name='ai_agent_ai_provide_696c3f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tenantaitaskmodel',
            constraint=models.UniqueConstraint(fields=('settings', 'task_type'), name='unique_tenant_ai_task_model'),
        ),
    ]
