# Generated by Django 5.0.9 on 2026-07-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_seed_ai_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='is_pricing_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('kimi', 'Kimi')], max_length=20),
        ),
    ]
