# Generated by Django 5.0.9 on 2026-08-04 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0006_aiproviderprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('task_type', models.CharField(choices=[('description_generation', 'Генерация описаний'), ('classification', 'Классификация товаров'), ('attribute_extraction', 'Извлечение характеристик'), ('fitment_resolution', 'Анализ совместимости')], max_length=40)),
                ('catalog_domain', models.CharField(blank=True, help_text='Пусто — шаблон подходит для любого домена каталога.', max_length=50)),
                ('marketplace', models.CharField(blank=True, help_text='Пусто — шаблон подходит для любого маркетплейса.', max_length=30)),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('system_prompt', models.TextField()),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('change_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Шаблон AI-промпта',
                'verbose_name_plural': 'Шаблоны AI-промптов',
                'ordering': ['task_type', 'catalog_domain', 'marketplace', '-version'],
            },
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='prompt_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='aiprompttemplate',
            constraint=models.UniqueConstraint(fields=('task_type', 'catalog_domain', 'marketplace', 'version'), name='unique_ai_prompt_scope_version'),
        ),
        migrations.AddConstraint(
            model_name='aiprompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('task_type', 'catalog_domain', 'marketplace'), name='unique_active_ai_prompt_scope'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_logs', to='ai_agent.aiprompttemplate'),
        ),
    ]
