# Generated by Django 5.0.9 on 2026-08-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0009_seed_auto_parts_description_prompt_v3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompttemplate',
            name='task_type',
            field=models.CharField(choices=[('description_generation', 'Генерация описаний'), ('classification', 'Классификация товаров'), ('attribute_extraction', 'Извлечение характеристик'), ('fitment_resolution', 'Анализ совместимости'), ('web_research', 'Интернет-исследование товара')], max_length=40),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='task_type',
            field=models.CharField(choices=[('description_generation', 'Генерация описаний'), ('classification', 'Классификация товаров'), ('attribute_extraction', 'Извлечение характеристик'), ('fitment_resolution', 'Анализ совместимости'), ('web_research', 'Интернет-исследование товара')], max_length=40),
        ),
        migrations.AlterField(
            model_name='tenantaitaskmodel',
            name='task_type',
            field=models.CharField(choices=[('description_generation', 'Генерация описаний'), ('classification', 'Классификация товаров'), ('attribute_extraction', 'Извлечение характеристик'), ('fitment_resolution', 'Анализ совместимости'), ('web_research', 'Интернет-исследование товара')], max_length=40),
        ),
    ]
