# Generated by Django 5.2.17 on 2026-08-13 00:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0016_seed_source_title_fitment_prompt_v8'),
        ('tenants', '0016_webhook_delivery_claim_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderOperation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('description_generation', 'Генерация описаний'), ('classification', 'Классификация товаров'), ('attribute_extraction', 'Извлечение характеристик'), ('fitment_resolution', 'Анализ совместимости'), ('web_research', 'Интернет-исследование товара')], max_length=40)),
                ('provider', models.CharField(max_length=20)),
                ('model_id', models.CharField(max_length=120)),
                ('reservation_key', models.CharField(max_length=160)),
                ('reserved_amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('charged_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('domain_type', models.CharField(choices=[('product', 'Товар'), ('web_research_run', 'Интернет-исследование')], max_length=40)),
                ('domain_reference', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('reserved', 'Зарезервировано'), ('pending_reconciliation', 'Требует сверки'), ('released', 'Резерв возвращён'), ('settled', 'Резерв списан')], db_index=True, default='reserved', max_length=30)),
                ('provider_error_code', models.CharField(blank=True, max_length=80)),
                ('terminal_reason', models.CharField(blank=True, max_length=120)),
                ('resolution_action', models.CharField(blank=True, choices=[('release', 'Вернуть резерв'), ('settle', 'Списать по фактическому потреблению'), ('settle_reserved', 'Списать зарезервированное')], max_length=30)),
                ('operator_note', models.TextField(blank=True)),
                ('validated_result', models.JSONField(blank=True, null=True)),
                ('apply_state', models.CharField(choices=[('not_required', 'Применение не требуется'), ('pending', 'Ожидает применения'), ('applied', 'Применено')], db_index=True, default='not_required', max_length=20)),
                ('network_started_at', models.DateTimeField(blank=True, null=True)),
                ('uncertainty_marked_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_provider_operations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Операция AI-провайдера',
                'verbose_name_plural': 'Операции AI-провайдеров',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='ai_op_tenant_status_idx'), models.Index(fields=['status', 'uncertainty_marked_at'], name='ai_op_uncertain_idx'), models.Index(fields=['status', 'network_started_at'], name='ai_op_network_started_idx'), models.Index(fields=['status', 'apply_state', 'created_at'], name='ai_op_apply_queue_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'reservation_key'), name='unique_tenant_ai_provider_reservation'), models.CheckConstraint(condition=models.Q(('reserved_amount__gte', 0)), name='ai_provider_reserved_nonnegative'), models.CheckConstraint(condition=models.Q(('charged_amount__isnull', True), ('charged_amount__gte', 0), _connector='OR'), name='ai_provider_charged_nonnegative')],
            },
        ),
    ]
