# Generated by Django 5.0.9 on 2026-05-10 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_options_alter_productimage_options_and_more'),
        ('tenants', '0003_alter_apikey_created_at_alter_apikey_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Формат: img_search:{article}:{brand}', max_length=200, unique=True, verbose_name='Ключ кеша')),
                ('results', models.JSONField(verbose_name='Результаты (JSON)')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Кеш поиска изображений',
                'verbose_name_plural': 'Кеш поиска изображений',
            },
        ),
        migrations.CreateModel(
            name='ImageSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=50, verbose_name='Источник')),
                ('query', models.CharField(max_length=500, verbose_name='Поисковый запрос')),
                ('confidence', models.CharField(blank=True, max_length=10, verbose_name='Уверенность запроса')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Найдено кандидатов')),
                ('accepted_count', models.PositiveSmallIntegerField(default=0, verbose_name='Принято')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Длительность (мс)')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_search_logs', to='products.product', verbose_name='Товар')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_search_logs', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Лог поиска изображений',
                'verbose_name_plural': 'Логи поиска изображений',
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='image_searc_tenant__948dbe_idx'), models.Index(fields=['product', 'created_at'], name='image_searc_product_944530_idx'), models.Index(fields=['source_id', 'created_at'], name='image_searc_source__ea6559_idx')],
            },
        ),
    ]
