# Generated by Django 5.0.9 on 2026-08-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0003_bravequota'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesearchlog',
            name='query_builder_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='Версия построителя запросов'),
        ),
        migrations.AddField(
            model_name='imagesearchlog',
            name='query_metrics',
            field=models.JSONField(blank=True, default=list, verbose_name='Метрики запросов'),
        ),
    ]
