# Generated by Django 5.0.9 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0004_imagesearchlog_query_builder_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSearchTask',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='image_search_tasks',
                        to='products.product',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='image_search_tasks',
                        to='tenants.tenant',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['tenant', '-created_at'],
                        name='img_task_tenant_created_idx',
                    ),
                    models.Index(
                        fields=['product', '-created_at'],
                        name='img_task_product_created_idx',
                    ),
                ],
            },
        ),
    ]
