# Generated by Django 5.0.9 on 2026-05-08 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('active_listings_count', models.PositiveIntegerField(default=0)),
                ('sku_count', models.PositiveIntegerField(default=0)),
                ('ai_credits_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Тенант',
                'verbose_name_plural': 'Тенанты',
                'indexes': [models.Index(fields=['slug'], name='tenants_ten_slug_63daca_idx'), models.Index(fields=['is_active'], name='tenants_ten_is_acti_8f654a_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(max_length=12)),
                ('key_hash', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'API-ключ',
                'verbose_name_plural': 'API-ключи',
                'indexes': [models.Index(fields=['key_hash'], name='tenants_api_key_has_617113_idx'), models.Index(fields=['tenant', 'is_active'], name='tenants_api_tenant__332b2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='operator', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь тенанта',
                'verbose_name_plural': 'Пользователи тенантов',
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
