# Generated by Django 5.0.9 on 2026-05-09 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(max_length=64)),
                ('events', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Вебхук-эндпоинт',
                'verbose_name_plural': 'Вебхук-эндпоинты',
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='tenants_web_tenant__cb497b_idx')],
            },
        ),
    ]
