# Generated by Django 5.0.9 on 2026-05-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_apikey_created_at_alter_apikey_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='catalog_domain',
            field=models.CharField(choices=[('auto_parts', 'Автозапчасти'), ('generic', 'Обычный каталог'), ('jewellery', 'Украшения'), ('apparel', 'Одежда'), ('other', 'Другое')], default='auto_parts', max_length=30, verbose_name='Домен каталога'),
        ),
    ]
