# Generated by Django 5.0.9 on 2026-05-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_catalog_domain_part_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='catalog_domain',
            field=models.CharField(choices=[('auto_parts', 'Автозапчасти'), ('mixed', 'Смешанный каталог'), ('generic', 'Обычный каталог'), ('jewellery', 'Украшения'), ('apparel', 'Одежда'), ('other', 'Другое')], default='auto_parts', max_length=30, verbose_name='Домен каталога'),
        ),
    ]
