# Generated by Django 5.0.9 on 2026-05-30 21:45

from django.db import migrations, models


def seed_catalog_domains(apps, schema_editor):
    CatalogDomain = apps.get_model('tenants', 'CatalogDomain')
    domains = [
        {
            'slug': 'auto_parts',
            'name': 'Автозапчасти',
            'short_name': 'Авто',
            'description': 'Каталоги автомобильных запчастей, OEM-кодов и применяемости.',
            'seo_title': 'Автозапчасти',
            'seo_description': 'Каталог автозапчастей с поддержкой обогащения, OEM-кодов и применяемости.',
            'seo_h1': 'Автозапчасти',
            'is_system': True,
            'sort_order': 10,
            'supports_auto_parts_enrichment': True,
            'requires_product_classification': False,
        },
        {
            'slug': 'mixed',
            'name': 'Смешанный каталог',
            'short_name': 'Смешанный',
            'description': 'Каталоги с товарами разных типов, где автозапчасти определяются на уровне товара.',
            'seo_title': 'Смешанный каталог',
            'seo_description': 'Смешанный каталог товаров с безопасной классификацией по типам.',
            'seo_h1': 'Смешанный каталог',
            'is_system': True,
            'sort_order': 20,
            'supports_auto_parts_enrichment': True,
            'requires_product_classification': True,
        },
        {
            'slug': 'generic',
            'name': 'Обычный каталог',
            'short_name': 'Общий',
            'description': 'Универсальные товары без domain-specific обогащения.',
            'seo_title': 'Обычный каталог',
            'seo_description': 'Универсальный каталог товаров.',
            'seo_h1': 'Обычный каталог',
            'is_system': True,
            'sort_order': 30,
        },
        {
            'slug': 'jewellery',
            'name': 'Украшения',
            'short_name': 'Украшения',
            'description': 'Ювелирные изделия и аксессуары.',
            'seo_title': 'Украшения',
            'seo_description': 'Каталог украшений и ювелирных изделий.',
            'seo_h1': 'Украшения',
            'is_system': True,
            'sort_order': 40,
        },
        {
            'slug': 'apparel',
            'name': 'Одежда',
            'short_name': 'Одежда',
            'description': 'Одежда, обувь и fashion-товары.',
            'seo_title': 'Одежда',
            'seo_description': 'Каталог одежды, обуви и fashion-товаров.',
            'seo_h1': 'Одежда',
            'is_system': True,
            'sort_order': 50,
        },
        {
            'slug': 'unknown',
            'name': 'Не определено',
            'short_name': 'Не ясно',
            'description': 'Системное состояние для товаров без уверенной классификации.',
            'seo_title': 'Не определено',
            'seo_description': 'Товары, которым ещё не определён тип каталога.',
            'seo_h1': 'Не определено',
            'is_system': True,
            'sort_order': 1000,
        },
    ]
    for data in domains:
        CatalogDomain.objects.update_or_create(slug=data['slug'], defaults=data)


def unseed_catalog_domains(apps, schema_editor):
    CatalogDomain = apps.get_model('tenants', 'CatalogDomain')
    CatalogDomain.objects.filter(
        slug__in=['auto_parts', 'mixed', 'generic', 'jewellery', 'apparel', 'unknown']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_add_mixed_catalog_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='catalog_domain',
            field=models.CharField(default='auto_parts', max_length=50, verbose_name='Домен каталога'),
        ),
        migrations.CreateModel(
            name='CatalogDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=60, verbose_name='Короткое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, verbose_name='SEO keywords')),
                ('seo_h1', models.CharField(blank=True, max_length=255, verbose_name='SEO H1')),
                ('canonical_path', models.CharField(blank=True, max_length=255, verbose_name='Canonical path')),
                ('og_title', models.CharField(blank=True, max_length=255, verbose_name='OG title')),
                ('og_description', models.TextField(blank=True, verbose_name='OG description')),
                ('og_image_url', models.URLField(blank=True, verbose_name='OG image URL')),
                ('meta_robots', models.CharField(default='index,follow', max_length=100, verbose_name='Meta robots')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системный')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('supports_auto_parts_enrichment', models.BooleanField(default=False, verbose_name='Разрешает обогащение автозапчастей')),
                ('requires_product_classification', models.BooleanField(default=False, verbose_name='Требует проверки домена товара')),
            ],
            options={
                'verbose_name': 'Домен каталога',
                'verbose_name_plural': 'Домены каталога',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='tenants_cat_slug_2181e0_idx'), models.Index(fields=['is_active', 'sort_order'], name='tenants_cat_is_acti_276005_idx')],
            },
        ),
        migrations.RunPython(seed_catalog_domains, unseed_catalog_domains),
    ]
