# Generated by Django 5.0.9 on 2026-05-31 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_tenant_catalog_domain_catalogdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCatalogDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включена')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_enablings', to='tenants.catalogdomain', verbose_name='Корневая категория')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_catalog_domains', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Корневая категория tenant-а',
                'verbose_name_plural': 'Корневые категории tenant-а',
                'ordering': ['domain__sort_order', 'domain__name'],
                'indexes': [models.Index(fields=['tenant', 'is_enabled'], name='tenants_ten_tenant__77b0ff_idx'), models.Index(fields=['domain', 'is_enabled'], name='tenants_ten_domain__1d333b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tenantcatalogdomain',
            constraint=models.UniqueConstraint(fields=('tenant', 'domain'), name='unique_tenant_catalog_domain'),
        ),
    ]
