# Generated by Django 5.0.9 on 2026-06-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_seed_base_catalog_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='catalog_domain',
            field=models.CharField(default='unknown', max_length=50, verbose_name='Домен каталога'),
        ),
    ]
