# Generated by Django 5.0.9 on 2026-07-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_rename_generic_mixed_domain_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ai_credit_limit_override',
            field=models.PositiveIntegerField(blank=True, help_text='Пусто — использовать лимит тарифного плана.', null=True, verbose_name='Индивидуальный месячный лимит AI-кредитов'),
        ),
    ]
