# Generated by Django 5.0.9 on 2026-08-09 06:39

import hashlib

import apps.tenants.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.utils import timezone


def apply_legacy_key_policy(apps, schema_editor):
    APIKey = apps.get_model('tenants', 'APIKey')
    revoked_at = timezone.now()
    occupied_hashes = set(APIKey.objects.values_list('key_hash', flat=True))

    duplicate_hashes = (
        APIKey.objects.values('key_hash')
        .annotate(key_count=Count('id'))
        .filter(key_count__gt=1)
    )
    for duplicate in duplicate_hashes.iterator():
        keys = APIKey.objects.filter(
            key_hash=duplicate['key_hash'],
        ).order_by('pk')
        for key in keys.iterator():
            attempt = 0
            while True:
                synthetic_hash = hashlib.sha256(
                    (
                        f'revoked-duplicate:{key.pk}:{attempt}:'
                        f'{key.key_hash}'
                    ).encode(),
                ).hexdigest()
                if synthetic_hash not in occupied_hashes:
                    break
                attempt += 1
            occupied_hashes.add(synthetic_hash)
            APIKey.objects.filter(pk=key.pk).update(
                key_hash=synthetic_hash,
                is_active=False,
                revoked_at=revoked_at,
            )

    APIKey.objects.filter(
        is_active=False,
        revoked_at__isnull=True,
    ).update(revoked_at=revoked_at)
    # Legacy keys carried neither a role nor auditable scopes, so granting them
    # inferred permissions would violate least privilege. Revoke them and force
    # an administrator to issue a deliberately scoped replacement.
    APIKey.objects.filter(is_active=True).update(
        is_active=False,
        revoked_at=revoked_at,
        role='viewer',
        scopes=['tenant:read'],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_webhook_outbox_and_encrypted_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apikey',
            name='tenants_api_key_has_617113_idx',
        ),
        migrations.AddField(
            model_name='apikey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=apps.tenants.models.default_api_key_expiry, verbose_name='Действует до'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отозван'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Отозвал'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('operator', 'Operator')], default='viewer', max_length=16, verbose_name='Роль интеграции'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='scopes',
            field=models.JSONField(default=apps.tenants.models.default_api_key_scopes, verbose_name='Scopes'),
        ),
        migrations.RunPython(
            apply_legacy_key_policy,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(max_length=64, unique=True, verbose_name='SHA256-хэш ключа'),
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['viewer', 'operator'])), name='api_key_limited_role'),
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.CheckConstraint(check=models.Q(('is_active', False), ('revoked_at__isnull', True), _connector='OR'), name='active_api_key_not_revoked'),
        ),
    ]
