# Generated by Django 5.0.9 on 2026-08-05 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0030_alter_productenrichmentfact_fact_type'),
        ('tenants', '0011_tenant_ai_credit_limit_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('need_review', 'Нужна проверка'), ('no_results', 'Ничего не найдено'), ('skipped', 'Не требуется'), ('failed', 'Ошибка')], db_index=True, default='queued', max_length=30, verbose_name='Статус')),
                ('trigger', models.CharField(choices=[('manual', 'Вручную'), ('parser_fallback', 'Fallback после каталогов')], default='manual', max_length=30, verbose_name='Причина запуска')),
                ('search_provider', models.SlugField(blank=True, verbose_name='Провайдер поиска')),
                ('ai_provider', models.CharField(blank=True, max_length=30, verbose_name='AI-провайдер')),
                ('ai_model', models.CharField(blank=True, max_length=120, verbose_name='AI-модель')),
                ('queries', models.JSONField(blank=True, default=list, verbose_name='Запросы')),
                ('coverage_before', models.JSONField(blank=True, default=dict, verbose_name='Полнота до исследования')),
                ('coverage_after', models.JSONField(blank=True, default=dict, verbose_name='Полнота после исследования')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='Найдено страниц')),
                ('claim_count', models.PositiveIntegerField(default=0, verbose_name='Найдено фактов')),
                ('generate_after', models.BooleanField(default=False, verbose_name='Сгенерировать описание после завершения')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_research_runs', to='products.product', verbose_name='Товар')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_research_runs', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Интернет-исследование товара',
                'verbose_name_plural': 'Интернет-исследования товаров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebResearchEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('query', models.CharField(max_length=500, verbose_name='Поисковый запрос')),
                ('rank', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Заголовок')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
                ('domain', models.CharField(db_index=True, max_length=255, verbose_name='Домен')),
                ('snippet', models.TextField(blank=True, verbose_name='Фрагмент')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='web_research.webresearchrun', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Доказательство интернет-исследования',
                'verbose_name_plural': 'Доказательства интернет-исследований',
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebResearchClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('claim_type', models.CharField(choices=[('brand', 'Бренд'), ('oem', 'OEM/Cross-код'), ('fitment', 'Применяемость'), ('fact', 'Факт/характеристика')], max_length=30, verbose_name='Тип')),
                ('payload', models.JSONField(default=dict, verbose_name='Структурированные данные')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Уверенность')),
                ('saved_model', models.CharField(blank=True, max_length=80, verbose_name='Модель результата')),
                ('saved_record_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID результата')),
                ('evidence', models.ManyToManyField(related_name='claims', to='web_research.webresearchevidence', verbose_name='Доказательства')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='web_research.webresearchrun', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Утверждение интернет-исследования',
                'verbose_name_plural': 'Утверждения интернет-исследований',
                'ordering': ['claim_type', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='webresearchrun',
            index=models.Index(fields=['tenant', '-created_at'], name='web_researc_tenant__bbf2d5_idx'),
        ),
        migrations.AddIndex(
            model_name='webresearchrun',
            index=models.Index(fields=['product', '-created_at'], name='web_researc_product_6baf0c_idx'),
        ),
        migrations.AddIndex(
            model_name='webresearchrun',
            index=models.Index(fields=['status', '-created_at'], name='web_researc_status_eca369_idx'),
        ),
        migrations.AddConstraint(
            model_name='webresearchrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('product',), name='unique_active_web_research_per_product'),
        ),
        migrations.AddConstraint(
            model_name='webresearchevidence',
            constraint=models.UniqueConstraint(fields=('run', 'url'), name='unique_web_research_evidence_url'),
        ),
    ]
