# Generated by Django 5.0.9 on 2026-08-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webresearchrun',
            name='status',
            field=models.CharField(
                choices=[
                    ('queued', 'В очереди'), ('running', 'Выполняется'),
                    ('need_review', 'Нужна проверка'), ('completed', 'Проверено'),
                    ('no_results', 'Ничего не найдено'), ('skipped', 'Не требуется'),
                    ('failed', 'Ошибка'),
                ],
                db_index=True, default='queued', max_length=30, verbose_name='Статус',
            ),
        ),
        migrations.AddField(
            model_name='webresearchevidence',
            name='provider_id',
            field=models.SlugField(blank=True, verbose_name='Провайдер поиска'),
        ),
        migrations.AddField(
            model_name='webresearchclaim',
            name='review_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Ожидает проверки'), ('approved', 'Одобрено'),
                    ('rejected', 'Отклонено'),
                ],
                default='pending', max_length=20, verbose_name='Проверка',
            ),
        ),
        migrations.CreateModel(
            name='WebSearchConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider_id', models.SlugField(unique=True, verbose_name='Провайдер')),
                ('display_name', models.CharField(max_length=120, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('priority', models.PositiveSmallIntegerField(default=100, verbose_name='Приоритет')),
                ('allowed_plan_slugs', models.JSONField(blank=True, default=list, help_text='Пустой список — доступно всем тарифам.', verbose_name='Доступно тарифам')),
                ('credentials_enc', models.BinaryField(blank=True, editable=False, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Безопасные настройки запроса без секретов.', verbose_name='Параметры')),
                ('requests_per_minute', models.PositiveIntegerField(default=60, verbose_name='Запросов в минуту')),
                ('monthly_request_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Месячный лимит запросов')),
                ('last_check_status', models.CharField(choices=[('not_checked', 'Не проверено'), ('ok', 'Подключено'), ('error', 'Ошибка')], default='not_checked', max_length=20, verbose_name='Состояние подключения')),
                ('last_check_message', models.CharField(blank=True, max_length=500, verbose_name='Результат проверки')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
            ],
            options={
                'verbose_name': 'Подключение интернет-поиска',
                'verbose_name_plural': 'Подключения интернет-поиска',
                'ordering': ['priority', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='WebSearchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider_id', models.SlugField(verbose_name='Провайдер')),
                ('query', models.CharField(max_length=500, verbose_name='Запрос')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('empty', 'Нет результатов'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], max_length=20, verbose_name='Статус')),
                ('result_count', models.PositiveSmallIntegerField(default=0, verbose_name='Результатов')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Длительность, мс')),
                ('retryable', models.BooleanField(default=False, verbose_name='Можно повторить')),
                ('error_code', models.CharField(blank=True, max_length=80, verbose_name='Код ошибки')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='Ошибка')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='web_research.websearchconnection', verbose_name='Подключение')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_attempts', to='web_research.webresearchrun', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Попытка интернет-поиска',
                'verbose_name_plural': 'Попытки интернет-поиска',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='websearchattempt',
            index=models.Index(fields=['provider_id', '-created_at'], name='websearch_provider_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='websearchattempt',
            index=models.Index(fields=['run', 'created_at'], name='websearch_run_created_idx'),
        ),
    ]
