# Generated by Django 5.0.9 on 2026-08-06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_product_catalog_category_manually_cleared'),
        ('tenants', '0011_tenant_ai_credit_limit_override'),
        ('web_research', '0002_search_provider_connections'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='webresearchrun',
            name='unique_active_web_research_per_product',
        ),
        migrations.AddField(
            model_name='webresearchevidence',
            name='raw_content',
            field=models.TextField(blank=True, verbose_name='Структурированное содержимое'),
        ),
        migrations.AddField(
            model_name='webresearchrun',
            name='offer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Найдено предложений'),
        ),
        migrations.AddField(
            model_name='webresearchrun',
            name='purpose',
            field=models.CharField(
                choices=[
                    ('enrichment', 'Техническое обогащение'),
                    ('pricing', 'Мониторинг цен'),
                    ('combined', 'Обогащение и цены'),
                ],
                db_index=True, default='enrichment', max_length=20, verbose_name='Назначение',
            ),
        ),
        migrations.AddField(
            model_name='webresearchrun',
            name='settings_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Снимок настроек поиска'),
        ),
        migrations.CreateModel(
            name='TenantWebResearchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('market_research_enabled', models.BooleanField(default=True, verbose_name='Мониторинг цен')),
                ('region_preset', models.CharField(choices=[('russia', 'Россия'), ('russia_cis', 'Россия и СНГ'), ('custom', 'Выбранные страны'), ('worldwide', 'Без ограничения')], default='russia', max_length=20, verbose_name='Регион поиска')),
                ('country_codes', models.JSONField(blank=True, default=list, verbose_name='Коды стран')),
                ('search_language', models.CharField(default='ru', max_length=10, verbose_name='Язык поиска')),
                ('include_marketplaces', models.BooleanField(default=True, verbose_name='Маркетплейсы')),
                ('include_used', models.BooleanField(default=False, verbose_name='Товары б/у')),
                ('include_preorder', models.BooleanField(default=True, verbose_name='Под заказ')),
                ('include_analogues', models.BooleanField(default=False, verbose_name='Аналоги')),
                ('exact_matches_only', models.BooleanField(default=True, verbose_name='Только точные совпадения')),
                ('preferred_domains', models.JSONField(blank=True, default=list, verbose_name='Приоритетные домены')),
                ('excluded_domains', models.JSONField(blank=True, default=list, verbose_name='Исключённые домены')),
                ('result_limit', models.PositiveSmallIntegerField(default=30, verbose_name='Лимит результатов')),
                ('price_ttl_hours', models.PositiveSmallIntegerField(default=24, verbose_name='Срок цены, часов')),
                ('display_currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_research_settings', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Настройки интернет-исследования тенанта',
                'verbose_name_plural': 'Настройки интернет-исследования тенантов',
            },
        ),
        migrations.CreateModel(
            name='CompetitorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider_id', models.SlugField(blank=True, verbose_name='Провайдер')),
                ('seller_name', models.CharField(blank=True, max_length=255, verbose_name='Продавец')),
                ('domain', models.CharField(db_index=True, max_length=255, verbose_name='Домен')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
                ('dedupe_key', models.CharField(db_index=True, max_length=64, verbose_name='Ключ дедупликации')),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=150, verbose_name='Регион')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Название')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('matched_code', models.CharField(blank=True, max_length=100, verbose_name='Совпавший код')),
                ('match_type', models.CharField(choices=[('exact', 'Точное совпадение'), ('cross', 'Совпадение по OEM/Cross-коду'), ('analogue', 'Возможный аналог'), ('review', 'Требуется проверка')], db_index=True, default='review', max_length=20, verbose_name='Тип совпадения')),
                ('match_confidence', models.FloatField(default=0.0, verbose_name='Точность совпадения')),
                ('match_reasons', models.JSONField(blank=True, default=list, verbose_name='Причины совпадения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Исходная цена')),
                ('currency', models.CharField(max_length=3, verbose_name='Исходная валюта')),
                ('normalized_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Нормализованная цена')),
                ('normalized_currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта сравнения')),
                ('is_price_from', models.BooleanField(default=False, verbose_name='Цена от')),
                ('availability', models.CharField(choices=[('unknown', 'Наличие не указано'), ('in_stock', 'В наличии'), ('preorder', 'Под заказ'), ('out_of_stock', 'Нет в наличии')], db_index=True, default='unknown', max_length=20, verbose_name='Наличие')),
                ('availability_text', models.CharField(blank=True, max_length=255, verbose_name='Текст наличия')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у'), ('unknown', 'Не указано')], db_index=True, default='unknown', max_length=20, verbose_name='Состояние')),
                ('delivery_text', models.CharField(blank=True, max_length=500, verbose_name='Доставка')),
                ('review_status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('verified', 'Подтверждено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Проверка')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Проверено')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Актуально до')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='web_research.webresearchevidence', verbose_name='Доказательство')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_offers', to='products.product', verbose_name='Товар')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='web_research.webresearchrun', verbose_name='Исследование')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_offers', to='tenants.tenant', verbose_name='Тенант')),
            ],
            options={
                'verbose_name': 'Рыночное предложение',
                'verbose_name_plural': 'Рыночные предложения',
                'ordering': ['normalized_price', '-captured_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='webresearchrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running']), ('purpose', 'enrichment')), fields=('product',), name='unique_active_enrichment_research_per_product'),
        ),
        migrations.AddConstraint(
            model_name='webresearchrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running']), ('purpose__in', ['pricing', 'combined'])), fields=('product',), name='unique_active_pricing_research_per_product'),
        ),
        migrations.AddIndex(
            model_name='competitoroffer',
            index=models.Index(fields=['tenant', 'product', '-captured_at'], name='web_researc_tenant__e0c32d_idx'),
        ),
        migrations.AddIndex(
            model_name='competitoroffer',
            index=models.Index(fields=['tenant', 'product', 'review_status', 'expires_at'], name='web_researc_tenant__b20760_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitoroffer',
            constraint=models.UniqueConstraint(fields=('run', 'dedupe_key'), name='unique_competitor_offer_per_run'),
        ),
    ]
