# Generated by Django 5.0.9 on 2026-05-08 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplaces', '0002_marketplaceaccount_listing'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('datasource_import', 'Импорт данных'), ('description_gen', 'Генерация описания'), ('listing_publish', 'Публикация'), ('listing_update', 'Обновление'), ('listing_price_update', 'Обновление цены'), ('listing_unpublish', 'Снятие с публикации'), ('listing_delete', 'Удаление'), ('listing_error', 'Ошибка листинга'), ('moderation', 'Модерация'), ('billing_event', 'Биллинг'), ('anti_ban_trigger', 'Анти-бан'), ('rate_limit_hit', 'Rate limit')], max_length=30)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warn', 'Предупреждение'), ('error', 'Ошибка')], max_length=10)),
                ('message', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='marketplaces.listing')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='sync_synclo_tenant__51f074_idx'), models.Index(fields=['tenant', 'event_type', 'status'], name='sync_synclo_tenant__62a885_idx')],
            },
        ),
    ]
