# Generated by Django 5.0.9 on 2026-06-06 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0004_alter_avitocategory_options_and_more'),
        ('products', '0024_alter_productbulkactionjob_action'),
        ('sync', '0001_initial'),
        ('tenants', '0010_rename_generic_mixed_domain_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='synclog',
            options={'verbose_name': 'Лог синхронизации', 'verbose_name_plural': 'Логи синхронизации'},
        ),
        migrations.AlterField(
            model_name='synclog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время события'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='event_type',
            field=models.CharField(choices=[('datasource_import', 'Импорт данных'), ('description_gen', 'Генерация описания'), ('listing_publish', 'Публикация'), ('listing_update', 'Обновление'), ('listing_price_update', 'Обновление цены'), ('listing_unpublish', 'Снятие с публикации'), ('listing_delete', 'Удаление'), ('listing_error', 'Ошибка листинга'), ('moderation', 'Модерация'), ('billing_event', 'Биллинг'), ('anti_ban_trigger', 'Анти-бан'), ('rate_limit_hit', 'Rate limit')], max_length=30, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='marketplaces.listing', verbose_name='Листинг'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='payload',
            field=models.JSONField(default=dict, verbose_name='Payload (JSON)'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('warn', 'Предупреждение'), ('error', 'Ошибка')], max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='tenants.tenant', verbose_name='Тенант'),
        ),
    ]
