# Generated by Django 5.0.9 on 2026-05-08 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avito_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_leaf', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='marketplaces.avitocategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.CharField(default='avito', max_length=50)),
                ('category_source', models.CharField(max_length=300)),
                ('category_target', models.CharField(max_length=200)),
                ('category_id', models.IntegerField()),
                ('attributes_map', models.JSONField(default=dict)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'marketplace', 'category_source')},
            },
        ),
    ]
