# Generated by Django 5.0.9 on 2026-05-08 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.CharField(choices=[('avito', 'Avito')], default='avito', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('external_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('credentials_enc', models.BinaryField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('requests_this_hour', models.PositiveIntegerField(default=0)),
                ('hour_bucket_reset_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_accounts', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'marketplace', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('external_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('active', 'Активно'), ('rejected', 'Отклонено'), ('archived', 'В архиве'), ('deleted', 'Удалено'), ('requires_review', 'Требует проверки'), ('limit_reached', 'Лимит достигнут')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description_ai', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('price_on_listing', models.DecimalField(decimal_places=2, max_digits=12)),
                ('publish_idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='tenants.tenant')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplaces.marketplaceaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='marketplace_tenant__91bc0a_idx'), models.Index(fields=['account', 'status'], name='marketplace_account_c26c87_idx'), models.Index(fields=['next_retry_at'], name='marketplace_next_re_020554_idx')],
                'unique_together': {('tenant', 'product', 'account')},
            },
        ),
    ]
