# Generated by Django 5.0.9 on 2026-05-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0002_marketplaceaccount_listing'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('contacts', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='marketplaces.listing')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_stats', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'date'], name='marketplace_tenant__ef65d2_idx')],
                'unique_together': {('listing', 'date')},
            },
        ),
    ]
