# Generated by Django 5.0.9 on 2026-06-06 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0003_listing_stats'),
        ('products', '0024_alter_productbulkactionjob_action'),
        ('tenants', '0010_rename_generic_mixed_domain_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avitocategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория Avito', 'verbose_name_plural': 'Категории Avito'},
        ),
        migrations.AlterModelOptions(
            name='categorymapping',
            options={'verbose_name': 'Маппинг категорий', 'verbose_name_plural': 'Маппинг категорий'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Листинг', 'verbose_name_plural': 'Листинги'},
        ),
        migrations.AlterModelOptions(
            name='marketplaceaccount',
            options={'verbose_name': 'Avito-аккаунт', 'verbose_name_plural': 'Avito-аккаунты'},
        ),
        migrations.AlterField(
            model_name='avitocategory',
            name='avito_id',
            field=models.IntegerField(unique=True, verbose_name='ID категории Avito'),
        ),
        migrations.AlterField(
            model_name='avitocategory',
            name='is_leaf',
            field=models.BooleanField(default=False, verbose_name='Конечная категория'),
        ),
        migrations.AlterField(
            model_name='avitocategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='avitocategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='marketplaces.avitocategory', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='categorymapping',
            name='attributes_map',
            field=models.JSONField(default=dict, verbose_name='Маппинг атрибутов'),
        ),
        migrations.AlterField(
            model_name='categorymapping',
            name='category_id',
            field=models.IntegerField(verbose_name='ID категории Avito'),
        ),
        migrations.AlterField(
            model_name='categorymapping',
            name='category_source',
            field=models.CharField(max_length=300, verbose_name='Категория источника'),
        ),
        migrations.AlterField(
            model_name='categorymapping',
            name='category_target',
            field=models.CharField(max_length=200, verbose_name='Категория Avito'),
        ),
        migrations.AlterField(
            model_name='categorymapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='categorymapping',
            name='marketplace',
            field=models.CharField(default='avito', max_length=50, verbose_name='Маркетплейс'),
        ),
        migrations.AlterField(
            model_name='categorymapping',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AlterField(
            model_name='categorymapping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='categorymapping',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Версия маппинга'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplaces.marketplaceaccount', verbose_name='Аккаунт Avito'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность AI (0–1)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description_ai',
            field=models.TextField(blank=True, verbose_name='AI-описание'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID объявления Avito'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на Avito'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_on_listing',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена на объявлении, ₽'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='publish_idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отклонения'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество попыток'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('active', 'Активно'), ('rejected', 'Отклонено'), ('archived', 'В архиве'), ('deleted', 'Удалено'), ('requires_review', 'Требует проверки'), ('limit_reached', 'Лимит достигнут')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Заголовок объявления'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='listingstats',
            name='contacts',
            field=models.PositiveIntegerField(default=0, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='listingstats',
            name='ctr',
            field=models.FloatField(default=0.0, verbose_name='CTR'),
        ),
        migrations.AlterField(
            model_name='listingstats',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='listingstats',
            name='impressions',
            field=models.PositiveIntegerField(default=0, verbose_name='Показы'),
        ),
        migrations.AlterField(
            model_name='listingstats',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='marketplaces.listing', verbose_name='Листинг'),
        ),
        migrations.AlterField(
            model_name='listingstats',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_stats', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AlterField(
            model_name='listingstats',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='credentials_enc',
            field=models.BinaryField(verbose_name='Токены доступа (зашифровано)'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='external_id',
            field=models.CharField(max_length=100, verbose_name='ID пользователя на Avito'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='hour_bucket_reset_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сброс счётчика запросов'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace',
            field=models.CharField(choices=[('avito', 'Avito')], default='avito', max_length=50, verbose_name='Маркетплейс'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название аккаунта'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='requests_this_hour',
            field=models.PositiveIntegerField(default=0, verbose_name='Запросов за текущий час'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_accounts', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Токен истекает'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
