# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0004_alter_avitocategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceaccount',
            name='default_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес по умолчанию'),
        ),
        migrations.AddField(
            model_name='marketplaceaccount',
            name='default_contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='marketplaceaccount',
            name='default_manager_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='marketplaceaccount',
            name='default_seller_address_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID адреса продавца Avito по умолчанию'),
        ),
        migrations.AddField(
            model_name='listing',
            name='address_override',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес объявления'),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_phone_override',
            field=models.CharField(blank=True, max_length=50, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='listing',
            name='manager_name_override',
            field=models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller_address_id_override',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID адреса продавца Avito'),
        ),
    ]
