# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0005_avito_placement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bulk_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Массово назначенный адрес'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bulk_contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Массово назначенный телефон'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bulk_manager_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Массово назначенное контактное лицо'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bulk_seller_address_id',
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name='Массово назначенный ID адреса продавца Avito',
            ),
        ),
    ]
