# Generated by Codex on 2026-06-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0006_listing_bulk_placement_fields'),
        ('tenants', '0010_rename_generic_mixed_domain_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplacePlacementAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('seller_address_id', models.CharField(blank=True, max_length=100, verbose_name='ID адреса Avito')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Регион/адрес размещения')),
                ('manager_name', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Контактный телефон')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='placement_addresses',
                        to='marketplaces.marketplaceaccount',
                        verbose_name='Аккаунт Avito',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='marketplace_placement_addresses',
                        to='tenants.tenant',
                        verbose_name='Тенант',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Адрес размещения',
                'verbose_name_plural': 'Адреса размещения',
                'ordering': ['account', '-is_default', 'name'],
                'unique_together': {('tenant', 'account', 'name')},
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='bulk_placement_address',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='bulk_listings',
                to='marketplaces.marketplaceplacementaddress',
                verbose_name='Массово назначенный адрес размещения',
            ),
        ),
        migrations.AddField(
            model_name='listing',
            name='placement_address',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='manual_listings',
                to='marketplaces.marketplaceplacementaddress',
                verbose_name='Адрес размещения',
            ),
        ),
    ]
