# Generated by Django 5.0.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0008_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Черновик'),
                    ('queued', 'В очереди'),
                    ('pending', 'На модерации Avito'),
                    ('active', 'Активно'),
                    ('rejected', 'Отклонено'),
                    ('archived', 'В архиве'),
                    ('deleted', 'Удалено'),
                    ('requires_review', 'Требует проверки'),
                    ('limit_reached', 'Лимит достигнут'),
                ],
                default='draft',
                max_length=20,
                verbose_name='Статус',
            ),
        ),
    ]
