# Generated by Django 5.2.17 on 2026-08-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0019_soft_delete_core_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='next_status_check_at',
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name='Следующая проверка статуса',
            ),
        ),
        migrations.AddField(
            model_name='listing',
            name='remote_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('active', 'Активно на площадке'),
                    ('rejected', 'Отклонено площадкой'),
                    ('blocked', 'Заблокировано площадкой'),
                    ('removed', 'Удалено с площадки'),
                    ('archived', 'В архиве площадки'),
                    ('other', 'Другой нормализованный статус'),
                ],
                editable=False,
                max_length=32,
                null=True,
                verbose_name='Последний статус на площадке',
            ),
        ),
        migrations.AddField(
            model_name='listing',
            name='remote_status_checked_at',
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name='Статус на площадке проверен',
            ),
        ),
        migrations.AddField(
            model_name='listing',
            name='status_check_claim_token',
            field=models.UUIDField(
                blank=True,
                editable=False,
                null=True,
                verbose_name='Токен batch-проверки статуса',
            ),
        ),
        migrations.AddField(
            model_name='listing',
            name='status_check_claimed_until',
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name='Lease проверки статуса истекает',
            ),
        ),
        migrations.AddField(
            model_name='marketplaceaccount',
            name='status_batch_claim_token',
            field=models.UUIDField(
                blank=True,
                editable=False,
                null=True,
                verbose_name='Токен владельца проверки статусов',
            ),
        ),
        migrations.AddField(
            model_name='marketplaceaccount',
            name='status_batch_claimed_until',
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name='Lease проверки статусов истекает',
            ),
        ),
        migrations.AddField(
            model_name='marketplaceaccount',
            name='status_batch_cooldown_until',
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name='Проверки статусов приостановлены до',
            ),
        ),
        migrations.AddField(
            model_name='marketplaceaccount',
            name='status_batch_due_at',
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name='Следующая проверка статусов аккаунта',
            ),
        ),
    ]
