# Generated by Django 5.2.17 on 2026-08-25 16:48

import datetime
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0028_feed_run_source_intent_unique'),
        ('tenants', '0016_webhook_delivery_claim_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceFeedArtifactUploadAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveSmallIntegerField(editable=False, verbose_name='Номер попытки загрузки')),
                ('revision', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Ревизия журнала загрузки')),
                ('state', models.CharField(choices=[('prepared', 'Подготовлена'), ('put_pending', 'PUT выполняется или требует сверки'), ('version_known', 'VersionId подтверждён'), ('verified', 'Версия проверена чтением'), ('attached', 'Артефакт атомарно привязан'), ('no_object', 'Отсутствие объекта подтверждено'), ('orphaned', 'Объект оставлен для безопасной очистки'), ('manual_review', 'Требуется ручная сверка')], default='prepared', editable=False, max_length=20, verbose_name='Состояние попытки загрузки')),
                ('put_resolution_source', models.CharField(blank=True, choices=[('put_response', 'Ответ одиночного PUT'), ('operator_reconciliation', 'Операторская сверка')], default='', editable=False, max_length=32, verbose_name='Источник разрешения PUT')),
                ('storage_bucket', models.CharField(editable=False, max_length=63, verbose_name='Приватный bucket')),
                ('expected_bucket_owner', models.CharField(editable=False, max_length=255, verbose_name='Ожидаемый владелец приватного bucket')),
                ('object_key', models.CharField(editable=False, max_length=255, verbose_name='Ключ объекта')),
                ('payload_sha256', models.CharField(editable=False, max_length=64, verbose_name='SHA-256 содержимого')),
                ('size_bytes', models.PositiveBigIntegerField(editable=False, verbose_name='Размер объекта в байтах')),
                ('projection_count', models.PositiveIntegerField(editable=False, verbose_name='Количество листингов в проекции')),
                ('content_type', models.CharField(editable=False, max_length=64, verbose_name='Content-Type объекта')),
                ('put_run_revision', models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='Ревизия запуска перед PUT')),
                ('object_version_id', models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Точный VersionId объекта')),
                ('put_started_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='PUT начат')),
                ('version_known_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='VersionId подтверждён')),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Версия проверена')),
                ('attached_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Артефакт привязан')),
                ('resolved_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Попытка окончательно разрешена')),
                ('safe_error_code', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Безопасный код ошибки')),
            ],
            options={
                'verbose_name': 'Попытка загрузки артефакта фида',
                'verbose_name_plural': 'Попытки загрузки артефактов фида',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceFeedFetchEvidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Redirect выдан')),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('HEAD', 'HEAD')], editable=False, max_length=4, verbose_name='HTTP-метод')),
                ('accepted_token_key_id', models.CharField(editable=False, max_length=32, verbose_name='Принятый ID capability-ключа')),
                ('capability_revision', models.PositiveBigIntegerField(editable=False, verbose_name='Ревизия capability token')),
                ('endpoint_revision', models.PositiveBigIntegerField(editable=False, verbose_name='Ревизия stable endpoint')),
                ('source_intent_revision', models.PositiveBigIntegerField(editable=False, verbose_name='Ревизия намерения фида')),
                ('run_revision', models.PositiveBigIntegerField(editable=False, verbose_name='Ревизия запуска фида')),
                ('redirect_status', models.PositiveSmallIntegerField(default=307, editable=False, verbose_name='HTTP-статус redirect')),
                ('redirect_expires_at', models.DateTimeField(editable=False, verbose_name='Redirect истекает')),
            ],
            options={
                'verbose_name': 'Свидетельство выдачи артефакта фида',
                'verbose_name_plural': 'Свидетельства выдачи артефактов фида',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceFeedPutReconciliationAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pre_revision', models.PositiveBigIntegerField(editable=False)),
                ('post_revision', models.PositiveBigIntegerField(editable=False)),
                ('from_state', models.CharField(editable=False, max_length=20)),
                ('to_state', models.CharField(editable=False, max_length=20)),
                ('outcome', models.CharField(choices=[('no_object_by_reviewed_settlement_policy', 'Объект не найден после выдержки'), ('version_known', 'VersionId подтверждён'), ('manual_review', 'Требуется ручная сверка')], editable=False, max_length=48)),
                ('decision_code', models.CharField(blank=True, editable=False, max_length=64)),
                ('version_id_captured', models.BooleanField(editable=False)),
                ('origin_process_identity_digest', models.CharField(editable=False, max_length=64)),
                ('operator_identity_digest', models.CharField(editable=False, max_length=64)),
                ('evidence_digest', models.CharField(editable=False, max_length=64)),
                ('digest_scheme_revision', models.CharField(editable=False, max_length=64)),
                ('identity_digest_key_revision', models.CharField(editable=False, max_length=64)),
                ('adapter_policy_revision', models.CharField(editable=False, max_length=64)),
                ('canary_policy_revision', models.CharField(editable=False, max_length=64)),
                ('origin_process_terminated_at', models.DateTimeField(editable=False)),
                ('reconciliation_started_at', models.DateTimeField(editable=False)),
                ('decision_at', models.DateTimeField(editable=False)),
                ('settlement_window_seconds', models.PositiveIntegerField(editable=False)),
                ('pages_scanned', models.PositiveSmallIntegerField(editable=False)),
                ('entries_scanned', models.PositiveSmallIntegerField(editable=False)),
                ('exact_version_count', models.PositiveSmallIntegerField(editable=False)),
                ('exact_delete_marker_count', models.PositiveSmallIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Аудит операторской PUT-сверки',
                'verbose_name_plural': 'Аудит PUT-сверок',
            },
        ),
        migrations.AddField(
            model_name='marketplacefeedendpoint',
            name='artifact_promoted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Артефакт назначен текущим'),
        ),
        migrations.AddField(
            model_name='marketplacefeedendpoint',
            name='artifact_revision',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Ревизия текущего артефакта'),
        ),
        migrations.AddField(
            model_name='marketplacefeedrun',
            name='artifact_upload_attempt',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Попытка загрузки артефакта'),
        ),
        migrations.AddField(
            model_name='marketplacefeedrun',
            name='endpoint_revision',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='Ревизия stable endpoint при запуске'),
        ),
        migrations.AddField(
            model_name='marketplacefeedrun',
            name='predecessor_artifact_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='ID предыдущего артефакта фида'),
        ),
        migrations.CreateModel(
            name='MarketplaceFeedArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('upload_attempt', models.PositiveSmallIntegerField(editable=False, verbose_name='Попытка загрузки')),
                ('storage_bucket', models.CharField(editable=False, max_length=63, verbose_name='Приватный bucket')),
                ('object_key', models.CharField(editable=False, max_length=255, verbose_name='Ключ объекта')),
                ('object_version_id', models.CharField(editable=False, max_length=1024, verbose_name='VersionId объекта')),
                ('payload_sha256', models.CharField(editable=False, max_length=64, verbose_name='SHA-256 содержимого')),
                ('size_bytes', models.PositiveBigIntegerField(editable=False, verbose_name='Размер объекта в байтах')),
                ('listing_count', models.PositiveIntegerField(editable=False, verbose_name='Количество листингов')),
                ('content_type', models.CharField(editable=False, max_length=64, verbose_name='Content-Type объекта')),
                ('verification_method', models.CharField(editable=False, max_length=32, verbose_name='Метод проверки объекта')),
                ('verified_at', models.DateTimeField(editable=False, verbose_name='Объект проверен')),
                ('account', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='feed_artifacts', to='marketplaces.marketplaceaccount', verbose_name='Аккаунт маркетплейса')),
                ('endpoint', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='marketplaces.marketplacefeedendpoint', verbose_name='Stable feed endpoint')),
                ('run', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='marketplaces.marketplacefeedrun', verbose_name='Запуск фида')),
            ],
            options={
                'verbose_name': 'Проверенный артефакт фида',
                'verbose_name_plural': 'Проверенные артефакты фидов',
            },
        ),
        migrations.AddField(
            model_name='marketplacefeedendpoint',
            name='current_artifact',
            field=models.ForeignKey(blank=True, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_endpoints', to='marketplaces.marketplacefeedartifact', verbose_name='Текущий проверенный артефакт'),
        ),
        migrations.AddField(
            model_name='marketplacefeedrun',
            name='feed_artifact',
            field=models.ForeignKey(blank=True, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feed_runs', to='marketplaces.marketplacefeedartifact', verbose_name='Проверенный артефакт фида'),
        ),
        migrations.AddIndex(
            model_name='marketplacefeedendpoint',
            index=models.Index(condition=models.Q(('current_artifact__isnull', False)), fields=['current_artifact', 'public_id'], name='mkt_feed_ep_current_art'),
        ),
        migrations.AddIndex(
            model_name='marketplacefeedrun',
            index=models.Index(condition=models.Q(('feed_artifact__isnull', False)), fields=['feed_artifact', 'id'], name='mkt_feed_run_artifact'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedendpoint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artifact_promoted_at__isnull', True), ('artifact_revision', 0), ('current_artifact__isnull', True)), models.Q(('artifact_promoted_at__isnull', False), ('artifact_revision__gte', 1), ('current_artifact__isnull', False)), _connector='OR'), name='mkt_feed_ep_art_bundle'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artifact_upload_attempt', 0), ('endpoint_revision__isnull', True), ('feed_artifact__isnull', True), ('predecessor_artifact_id__isnull', True), ('source_intent_revision__isnull', True)), models.Q(('endpoint_revision__gte', 0), ('source_intent_revision__gte', 1)), _connector='OR'), name='mkt_feed_run_mode_bundle'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedrun',
            constraint=models.CheckConstraint(condition=models.Q(('feed_artifact__isnull', True), ('artifact_upload_attempt__gte', 1), _connector='OR'), name='mkt_feed_run_art_attempt'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedrun',
            constraint=models.CheckConstraint(condition=models.Q(('feed_artifact__isnull', True), ('predecessor_artifact_id__isnull', True), models.Q(('feed_artifact', models.F('predecessor_artifact_id')), _negated=True), _connector='OR'), name='mkt_feed_run_art_distinct'),
        ),
        migrations.AddField(
            model_name='marketplacefeedartifactuploadattempt',
            name='account',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='feed_artifact_upload_attempts', to='marketplaces.marketplaceaccount', verbose_name='Аккаунт маркетплейса'),
        ),
        migrations.AddField(
            model_name='marketplacefeedartifactuploadattempt',
            name='endpoint',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='artifact_upload_attempts', to='marketplaces.marketplacefeedendpoint', verbose_name='Stable feed endpoint'),
        ),
        migrations.AddField(
            model_name='marketplacefeedartifactuploadattempt',
            name='run',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='artifact_upload_attempts', to='marketplaces.marketplacefeedrun', verbose_name='Запуск фида'),
        ),
        migrations.AddField(
            model_name='marketplacefeedfetchevidence',
            name='artifact',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='fetch_evidence', to='marketplaces.marketplacefeedartifact', verbose_name='Выданный артефакт'),
        ),
        migrations.AddField(
            model_name='marketplacefeedfetchevidence',
            name='endpoint',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='fetch_evidence', to='marketplaces.marketplacefeedendpoint', verbose_name='Stable feed endpoint'),
        ),
        migrations.AddField(
            model_name='marketplacefeedputreconciliationaudit',
            name='attempt',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='put_reconciliation_audit', to='marketplaces.marketplacefeedartifactuploadattempt', verbose_name='Попытка загрузки'),
        ),
        migrations.AddIndex(
            model_name='marketplacefeedartifact',
            index=models.Index(fields=['endpoint', '-verified_at', 'id'], name='mkt_art_ep_verified'),
        ),
        migrations.AddIndex(
            model_name='marketplacefeedartifact',
            index=models.Index(fields=['account', '-verified_at', 'id'], name='mkt_art_acct_verified'),
        ),
        migrations.AddIndex(
            model_name='marketplacefeedartifact',
            index=models.Index(fields=['verified_at', 'id'], name='mkt_art_verified'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifact',
            constraint=models.UniqueConstraint(fields=('run', 'upload_attempt'), name='uniq_mkt_art_run_attempt'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifact',
            constraint=models.UniqueConstraint(fields=('storage_bucket', 'object_key'), name='uniq_mkt_art_object'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifact',
            constraint=models.CheckConstraint(condition=models.Q(('content_type', 'application/xml')), name='mkt_art_content_type'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifact',
            constraint=models.CheckConstraint(condition=models.Q(('verification_method', 'version_readback_sha256')), name='mkt_art_verify_method'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifact',
            constraint=models.CheckConstraint(condition=models.Q(('payload_sha256__regex', '^[0-9a-f]{64}$')), name='mkt_art_payload_sha'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifact',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 1), ('size_bytes__lte', 1073741824)), name='mkt_art_size'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifact',
            constraint=models.CheckConstraint(condition=models.Q(('listing_count__lte', 10000)), name='mkt_art_listing_count'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifact',
            constraint=models.CheckConstraint(condition=models.Q(('upload_attempt__gte', 1), ('upload_attempt__lte', 32767)), name='mkt_art_upload_attempt'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('object_version_id', ''), _negated=True), models.Q(('object_version_id__iregex', '^null$'), _negated=True)), name='mkt_art_version_present'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifact',
            constraint=models.CheckConstraint(condition=models.Q(('storage_bucket__regex', '^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$')), name='mkt_art_bucket_format'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifact',
            constraint=models.CheckConstraint(condition=models.Q(('object_key__startswith', 'private-feeds/v1/')), name='mkt_art_object_key'),
        ),
        migrations.AddIndex(
            model_name='marketplacefeedartifactuploadattempt',
            index=models.Index(fields=['state', 'updated_at', 'id'], name='mkt_upl_state_updated'),
        ),
        migrations.AddIndex(
            model_name='marketplacefeedartifactuploadattempt',
            index=models.Index(fields=['account', '-created_at', 'id'], name='mkt_upl_acct_created'),
        ),
        migrations.AddIndex(
            model_name='marketplacefeedartifactuploadattempt',
            index=models.Index(fields=['endpoint', '-created_at', 'id'], name='mkt_upl_ep_created'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.UniqueConstraint(fields=('run', 'attempt_no'), name='uniq_mkt_upl_run_attempt'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.UniqueConstraint(fields=('storage_bucket', 'object_key'), name='uniq_mkt_upl_object'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('prepared', 'put_pending', 'version_known', 'verified', 'attached', 'no_object', 'orphaned', 'manual_review'))), name='mkt_upl_state'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(('put_resolution_source__in', ('', 'put_response', 'operator_reconciliation'))), name='mkt_upl_resolution_src'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_no__gte', 1), ('attempt_no__lte', 32767)), name='mkt_upl_attempt'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(('payload_sha256__regex', '^[0-9a-f]{64}$')), name='mkt_upl_payload_sha'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 1), ('size_bytes__lte', 1073741824)), name='mkt_upl_size'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(('projection_count__lte', 10000)), name='mkt_upl_projection'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(('content_type', 'application/xml')), name='mkt_upl_content_type'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(('storage_bucket__regex', '^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$')), name='mkt_upl_bucket'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(('expected_bucket_owner__regex', '^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,254}$')), name='mkt_upl_bucket_owner'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(('object_key__startswith', 'private-feeds/v1/')), name='mkt_upl_object_key'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(('safe_error_code', ''), ('safe_error_code__regex', '^[a-z][a-z0-9_]{0,63}$'), _connector='OR'), name='mkt_upl_error_code'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('put_run_revision__isnull', True), ('put_started_at__isnull', True)), models.Q(('put_run_revision__isnull', False), ('put_started_at__isnull', False)), _connector='OR'), name='mkt_upl_put_bundle'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('object_version_id__isnull', True), ('version_known_at__isnull', True)), models.Q(('object_version_id__isnull', False), ('version_known_at__isnull', False), models.Q(('object_version_id', ''), _negated=True), models.Q(('object_version_id__iregex', '^null$'), _negated=True)), _connector='OR'), name='mkt_upl_version_bundle'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(('verified_at__isnull', True), ('object_version_id__isnull', False), _connector='OR'), name='mkt_upl_verified_version'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attached_at__isnull', True), ('object_version_id__isnull', True), ('put_run_revision__isnull', True), ('resolved_at__isnull', True), ('safe_error_code', ''), ('state', 'prepared'), ('verified_at__isnull', True)), models.Q(('attached_at__isnull', True), ('object_version_id__isnull', True), ('put_run_revision__isnull', False), ('resolved_at__isnull', True), ('safe_error_code', ''), ('state', 'put_pending'), ('verified_at__isnull', True)), models.Q(('attached_at__isnull', True), ('object_version_id__isnull', False), ('put_run_revision__isnull', False), ('resolved_at__isnull', True), ('safe_error_code', ''), ('state', 'version_known'), ('verified_at__isnull', True)), models.Q(('attached_at__isnull', True), ('object_version_id__isnull', False), ('put_run_revision__isnull', False), ('resolved_at__isnull', True), ('safe_error_code', ''), ('state', 'verified'), ('verified_at__isnull', False)), models.Q(('attached_at__isnull', False), ('object_version_id__isnull', False), ('put_run_revision__isnull', False), ('resolved_at__isnull', False), ('safe_error_code', ''), ('state', 'attached'), ('verified_at__isnull', False)), models.Q(('attached_at__isnull', True), ('object_version_id__isnull', True), ('resolved_at__isnull', False), ('state', 'no_object'), ('verified_at__isnull', True), models.Q(('safe_error_code', ''), _negated=True)), models.Q(('attached_at__isnull', True), ('object_version_id__isnull', False), ('put_run_revision__isnull', False), ('resolved_at__isnull', False), ('state', 'orphaned'), models.Q(('safe_error_code', ''), _negated=True)), models.Q(('attached_at__isnull', True), ('resolved_at__isnull', False), ('state', 'manual_review'), models.Q(('safe_error_code', ''), _negated=True)), _connector='OR'), name='mkt_upl_state_bundle'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedartifactuploadattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('put_started_at__isnull', True), ('put_started_at__gte', models.F('created_at')), _connector='OR'), models.Q(('version_known_at__isnull', True), ('version_known_at__gte', models.F('put_started_at')), _connector='OR'), models.Q(('verified_at__isnull', True), ('verified_at__gte', models.F('version_known_at')), _connector='OR'), models.Q(('attached_at__isnull', True), ('attached_at__gte', models.F('verified_at')), _connector='OR'), models.Q(('resolved_at__isnull', True), ('resolved_at__gte', models.F('created_at')), _connector='OR'), models.Q(('resolved_at__isnull', True), ('put_started_at__isnull', True), ('resolved_at__gte', models.F('put_started_at')), _connector='OR'), models.Q(('resolved_at__isnull', True), ('version_known_at__isnull', True), ('resolved_at__gte', models.F('version_known_at')), _connector='OR'), models.Q(('resolved_at__isnull', True), ('verified_at__isnull', True), ('resolved_at__gte', models.F('verified_at')), _connector='OR')), name='mkt_upl_time_order'),
        ),
        migrations.AddIndex(
            model_name='marketplacefeedfetchevidence',
            index=models.Index(fields=['endpoint', '-issued_at', 'id'], name='mkt_fetch_ep_issued'),
        ),
        migrations.AddIndex(
            model_name='marketplacefeedfetchevidence',
            index=models.Index(fields=['artifact', '-issued_at', 'id'], name='mkt_fetch_art_issued'),
        ),
        migrations.AddIndex(
            model_name='marketplacefeedfetchevidence',
            index=models.Index(fields=['-issued_at', 'id'], name='mkt_fetch_issued'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedfetchevidence',
            constraint=models.CheckConstraint(condition=models.Q(('request_method__in', ('GET', 'HEAD'))), name='mkt_fetch_method'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedfetchevidence',
            constraint=models.CheckConstraint(condition=models.Q(('redirect_status', 307)), name='mkt_fetch_status'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedfetchevidence',
            constraint=models.CheckConstraint(condition=models.Q(('redirect_expires_at__gt', models.F('issued_at'))), name='mkt_fetch_expiry'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedfetchevidence',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_token_key_id__regex', '^[A-Za-z0-9][A-Za-z0-9_.-]{0,31}$')), name='mkt_fetch_key_id'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedfetchevidence',
            constraint=models.CheckConstraint(condition=models.Q(('capability_revision__gte', 1), ('endpoint_revision__gte', 1), ('run_revision__gte', 0), ('source_intent_revision__gte', 1)), name='mkt_fetch_revisions'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedfetchevidence',
            constraint=models.CheckConstraint(condition=models.Q(('redirect_expires_at__lte', django.db.models.expressions.CombinedExpression(models.F('issued_at'), '+', models.Value(datetime.timedelta(seconds=300))))), name='mkt_fetch_ttl'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedputreconciliationaudit',
            constraint=models.CheckConstraint(condition=models.Q(('pre_revision__gte', 1)), name='mkt_put_aud_pre_revision'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedputreconciliationaudit',
            constraint=models.CheckConstraint(condition=models.Q(('post_revision', django.db.models.expressions.CombinedExpression(models.F('pre_revision'), '+', models.Value(1)))), name='mkt_put_aud_revision_step'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedputreconciliationaudit',
            constraint=models.CheckConstraint(condition=models.Q(('from_state', 'put_pending')), name='mkt_put_aud_from_state'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedputreconciliationaudit',
            constraint=models.CheckConstraint(condition=models.Q(('to_state__in', ('no_object', 'version_known', 'manual_review'))), name='mkt_put_aud_to_state'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedputreconciliationaudit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision_code', 'reviewed_settlement_no_object'), ('exact_delete_marker_count', 0), ('exact_version_count', 0), ('outcome', 'no_object_by_reviewed_settlement_policy'), ('to_state', 'no_object'), ('version_id_captured', False)), models.Q(('decision_code', ''), ('exact_delete_marker_count', 0), ('exact_version_count', 1), ('outcome', 'version_known'), ('to_state', 'version_known'), ('version_id_captured', True)), models.Q(('decision_code__in', ('put_reconcile_delete_marker', 'put_reconcile_multiple_versions', 'put_reconcile_unusable_version', 'put_reconcile_malformed_listing', 'put_reconcile_page_limit')), ('outcome', 'manual_review'), ('to_state', 'manual_review'), models.Q(('version_id_captured', False), models.Q(('exact_version_count__gte', 1), ('version_id_captured', True)), _connector='OR')), _connector='OR'), name='mkt_put_aud_decision_bundle'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedputreconciliationaudit',
            constraint=models.CheckConstraint(condition=models.Q(('origin_process_identity_digest__regex', '^[0-9a-f]{64}$'), ('operator_identity_digest__regex', '^[0-9a-f]{64}$'), ('evidence_digest__regex', '^[0-9a-f]{64}$')), name='mkt_put_aud_digests'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedputreconciliationaudit',
            constraint=models.CheckConstraint(condition=models.Q(('digest_scheme_revision__regex', '^[A-Za-z0-9][A-Za-z0-9_.:-]{0,63}$'), ('identity_digest_key_revision__regex', '^[A-Za-z0-9][A-Za-z0-9_.:-]{0,63}$'), ('adapter_policy_revision__regex', '^[A-Za-z0-9][A-Za-z0-9_.:-]{0,63}$'), ('canary_policy_revision__regex', '^[A-Za-z0-9][A-Za-z0-9_.:-]{0,63}$')), name='mkt_put_aud_policy_tokens'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedputreconciliationaudit',
            constraint=models.CheckConstraint(condition=models.Q(('entries_scanned__lte', 400), ('exact_delete_marker_count__lte', 400), ('exact_version_count__lte', 400), ('pages_scanned__gte', 1), ('pages_scanned__lte', 4), ('settlement_window_seconds', 900)), name='mkt_put_aud_bounded_counts'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedputreconciliationaudit',
            constraint=models.CheckConstraint(condition=models.Q(('exact_version_count__lte', models.F('entries_scanned')), ('exact_delete_marker_count__lte', models.F('entries_scanned')), ('entries_scanned__gte', django.db.models.expressions.CombinedExpression(models.F('exact_version_count'), '+', models.F('exact_delete_marker_count')))), name='mkt_put_aud_count_order'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedputreconciliationaudit',
            constraint=models.CheckConstraint(condition=models.Q(('reconciliation_started_at__gte', django.db.models.expressions.CombinedExpression(models.F('origin_process_terminated_at'), '+', models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.F('settlement_window_seconds'), '*', models.Value(datetime.timedelta(seconds=1))), output_field=models.DurationField()))), ('decision_at__gte', models.F('reconciliation_started_at'))), name='mkt_put_aud_time_order'),
        ),
        migrations.RemoveConstraint(
            model_name='marketplacefeedendpoint',
            name='mkt_feed_ep_state_legacy',
        ),
        migrations.RemoveConstraint(
            model_name='marketplacefeedendpoint',
            name='mkt_feed_ep_serve_guard',
        ),
        migrations.RemoveConstraint(
            model_name='marketplacefeedendpoint',
            name='mkt_feed_ep_private_dark',
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedendpoint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('profile_state__in', ('bridge_ready', 'migrating', 'update_unknown', 'verified')), _negated=True), models.Q(('storage_mode', 'legacy_bridge'), models.Q(('legacy_object_key', ''), _negated=True)), models.Q(('storage_mode', 'private_generation'), models.Q(models.Q(('serve_enabled', False), models.Q(('legacy_object_key', ''), _negated=True)), ('current_artifact__isnull', False), _connector='OR')), _connector='OR'), name='mkt_feed_ep_state_legacy'),
        ),
        migrations.AddConstraint(
            model_name='marketplacefeedendpoint',
            constraint=models.CheckConstraint(condition=models.Q(('serve_enabled', False), models.Q(('profile_state__in', ('bridge_ready', 'migrating', 'update_unknown', 'verified')), models.Q(models.Q(('storage_mode', 'legacy_bridge'), models.Q(('legacy_object_key', ''), _negated=True)), models.Q(('storage_mode', 'private_generation'), ('current_artifact__isnull', False)), _connector='OR')), _connector='OR'), name='mkt_feed_ep_serve_guard'),
        ),
    ]
