# Generated by Django 5.0.9 on 2026-05-08 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, default='', help_text='ID чата Telegram для отправки алертов', max_length=50)),
                ('notify_email', models.EmailField(blank=True, default='', help_text='Email для критических уведомлений и биллинга', max_length=254)),
                ('notify_on_error', models.BooleanField(default=True, help_text='Отправлять Telegram-уведомление при ошибках (level=error)')),
                ('notify_on_critical', models.BooleanField(default=True, help_text='Отправлять Telegram + Email при критических событиях (level=critical)')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
    ]
