# Generated by Django 5.0.9 on 2026-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantnotificationsettings',
            name='connect_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tenantnotificationsettings',
            name='connect_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantnotificationsettings',
            name='telegram_username',
            field=models.CharField(blank=True, default='', help_text='Username подключённого Telegram-аккаунта (для отображения)', max_length=100),
        ),
    ]
